-- Greek translator required

-----------
-- GREEK --
-----------
--
--
--
--

function HealBot_Lang_Options_grGR()
    HEALBOT_OPTIONS_HELP_TITLES={
                        -- Preset Colours
                                 ["PRESETCOLS"]="Prefix Col"..HEALBOT_enWORD_COLOUR_SUFFIX,
                                 ["PRESETCOLALIAS"]="Prefix Col"..HEALBOT_enWORD_COLOUR_SUFFIX.." Alias",
                                 ["PRESETCOLSET"]="Preset Col"..HEALBOT_enWORD_COLOUR_SUFFIX,
                                 ["PRESETCOLSELECT"]="Preset Col"..HEALBOT_enWORD_COLOUR_SUFFIX.." Select",
                                 ["PRESETCOLCANCEL"]="Preset Col"..HEALBOT_enWORD_COLOUR_SUFFIX.." Cancel",
                        -- General tab
                                 ["HIDEOPTIONBUTTON"]=HEALBOT_OPTIONS_HIDEOPTIONS,
                                 ["RIGHTTOOPENOPTIONS"]=HEALBOT_OPTIONS_RIGHTBOPTIONS,
                                 ["SHOWMINIMAPBUTTON"]=HEALBOT_OPTIONS_SHOWMINIMAPBUTTON,
                                 ["ENABLEFASTHEALTH"]=HEALBOT_OPTIONS_ENABLELIBQH,
                                 ["QUERYTALENTS"]=HEALBOT_OPTIONS_QUERYTALENTS,
                                 ["ENABLEAUTOCOMBAT"]=HEALBOT_OPTIONS_ENABLEAUTOCOMBAT,
                                 ["IGNOREAURAEVENTS"]=HEALBOT_OPTION_IGNORE_AURA_RESTED,
                                 ["DISABLEHEALBOT"]=HEALBOT_OPTIONS_DISABLEHEALBOT,
                                 ["DISABLEHEALBOTSOLO"]=HEALBOT_OPTIONS_DISABLEHEALBOT,
                                 ["ADJUSTMAXHLTH"]=HEALBOT_OPTION_ADJUST_MAX_HEALTH,
                                 ["OPTIONSOPACITY"]=HEALBOT_OPTIONS_OPTIONSOPACITY,
                                 ["INTERNALTIMERS"]=HEALBOT_OPTIONS_RANGECHECKFREQ,
                                 ["LANG"]=HEALBOT_OPTIONS_LANG,
                                 ["SETLANG"]=HEALBOT_OPTIONS_LANG,
                                 ["CMDS"]=HEALBOT_OPTIONS_COMMANDS,
                                 ["RUNCMDS"]=HEALBOT_OPTIONS_COMMANDS,
                                 ["PROFILE"]="Profile",
                                 ["SETPROFILE"]="Profile",
								 ["OPTTHEME"]=HEALBOT_OPTIONS_THEME,
                                 ["CLASSTYPES"]="Class type configuration",
                        -- Overrides tab
                                 ["OVERRIDESEFFECTS"]="Overrides Effects tab.",
                                 ["OVERRIDESPROT"]="Overrides Protection tab.",
                                 ["OVERRIDESCHAT"]="Overrides Chat tab.",
                                 ["OVERRIDESFRAMES"]="Overrides Frames tab.",
                                 ["OVERRIDESEFFECTSUSE"]=HEALBOT_OPTIONS_OVERRIDE_EFFECTS,
                        -- Spells tab
                                 ["SETSPELLSFOR"]=HEALBOT_OPTIONS_SETSPELLS,
                                 ["ALWAYSUSEENABLED"]=HEALBOT_OPTIONS_ENABLEHEALTHY,
                                 ["SPELLSBUTTON"]=HEALBOT_OPTIONS_COMBOBUTTON,
                                 ["SPELLSBUTTONCAST"]=HEALBOT_OPTIONS_BUTTONCASTMETHOD,
                                 ["SPELLSAVOIDBLUE"]="Avoid Blue Cursor",
                                 ["SPELLSAUTOTARGET"]="Auto Target",
                                 ["SPELLSAUTOTRINKET"]=HEALBOT_OPTIONS_COMBOAUTOTRINKET,
                                 ["SPELLSBUTTONCLICK"]=HEALBOT_OPTIONS_CLICK,
                                 ["SPELLSBUTTONSHIFTCLICK"]=HEALBOT_OPTIONS_SHIFT.." "..HEALBOT_OPTIONS_CLICK,
                                 ["SPELLSBUTTONCTRLCLICK"]=HEALBOT_OPTIONS_CTRL.." "..HEALBOT_OPTIONS_CLICK,
                                 ["SPELLSBUTTONALTCLICK"]=HEALBOT_OPTIONS_ALT.." "..HEALBOT_OPTIONS_CLICK,
                                 ["SPELLSBUTTONSHIFTCTRLCLICK"]=HEALBOT_OPTIONS_SHIFT.." "..HEALBOT_OPTIONS_CTRL.." "..HEALBOT_OPTIONS_CLICK,
                                 ["SPELLSBUTTONSHIFTALTCLICK"]=HEALBOT_OPTIONS_SHIFT.." "..HEALBOT_OPTIONS_ALT.." "..HEALBOT_OPTIONS_CLICK,
                                 ["SPELLSBUTTONCTRLALTCLICK"]=HEALBOT_OPTIONS_CTRL.." "..HEALBOT_OPTIONS_ALT.." "..HEALBOT_OPTIONS_CLICK,
                                 ["SPELLSHELPSELECT"]="Spell Selector",
                                 ["SPELLSSELECTSPELL"]=HEALBOT_OPTIONS_TAB_SPELLS,
                                 ["SPELLSSELECTMACRO"]=HEALBOT_WORD_MACROS,
                                 ["SPELLSSELECTITEMS"]=HEALBOT_OPTIONS_ITEMS,
                                 ["SPELLSSELECTCMDS"]=HEALBOT_WORD_COMMANDS,
                                 ["SPELLSSELECTCANCEL"]=HEALBOT_WORD_CANCEL,
                                 ["SMARTCAST"]=HEALBOT_OPTIONS_ENABLESMARTCAST,
                                 ["SMARTCASTAVOIDPVP"]=HEALBOT_OPTIONS_PROTECTPVP,
                                 ["SMARTCASTDEBUFF"]=HEALBOT_OPTIONS_SMARTCASTDISPELL,
                                 ["SMARTCASTBUFF"]=HEALBOT_OPTIONS_SMARTCASTBUFF,
                                 ["SMARTCASTHEAL"]=HEALBOT_OPTIONS_SMARTCASTHEAL,
                                 ["SMARTCASTRES"]="Cast resurrection",
                        -- Skins top
                                 ["SELECTSKIN"]=HEALBOT_OPTIONS_EXPORTSKIN,
                                 ["DELSKIN"]="Delete Skin",
                                 ["NEWSKIN"]=HEALBOT_OPTIONS_NEWSKINTEXT,
                                 ["SAVENEWSKIN"]="Save new skin",
                                 ["SELECTFRAME"]="Select Frame",
                                 ["FRAMEAPPLYTAB"]=HEALBOT_OPTIONS_SET_ALL_FRAMES,
                        -- Skins General tab
                                 ["SKINDEFAULTFOR"]=HEALBOT_OPTIONS_SKINDEFAULTFOR,
                                 ["STICKFRAMES"]=HEALBOT_OPTIONS_STICKYFRAMES,
                                 ["STICKSENSITIVITY"]=HEALBOT_OPTIONS_STICKYFRAMES.." Sensitivity",
                                 ["HIDEBLIZPARTYFRAMES"]=HEALBOT_OPTIONS_HIDEPARTYFRAMES,
                                 ["HIDEBLIZBOSSFRAMES"]=HEALBOT_OPTIONS_HIDEMINIBOSSFRAMES,
                                 ["HIDEBLIZRAIDFRAMES"]=HEALBOT_OPTIONS_HIDERAIDFRAMES,
                        -- Skins Effects tab
                                 ["USEFLUIDBARS"]=HEALBOT_OPTION_USEFLUIDBARS,
                                 ["FLUIDBARSREFRESHSPEED"]=HEALBOT_OPTION_BARUPDFREQ,
                                 ["HEALBARSAGGROBARFLASHFREQ"]=HEALBOT_OPTIONS_AGGROFLASHFREQ,
                                 ["HEALBARSAGGROBARFLASHMIN"]=HEALBOT_OPTIONS_AGGROFLASHALPHA.." "..HEALBOT_WORDS_MIN,
                                 ["HEALBARSAGGROBARFLASHMAX"]=HEALBOT_OPTIONS_AGGROFLASHALPHA.." "..HEALBOT_WORDS_MAX,
                        -- Skins Protection tab
                                 ["USECRASHPROT"]=HEALBOT_OPTIONS_CRASHPROT,
                                 ["USECRASHPROTGENERALMACRO"]=HEALBOT_OPTIONS_USEGENERALMACRO,
                                 ["USECRASHPROTBASEMACRO"]=HEALBOT_CP_MACRO_BASE,
                                 ["USECRASHPROTLOGONDURATION"]=HEALBOT_CP_STARTTIME,
                                 ["USECOMBATPROT"]=HEALBOT_OPTIONS_COMBATPROT,
                                 ["USECOMBATPROTGROUP"]=HEALBOT_OPTIONS_COMBATPROT,
                                 ["USECOMBATPROTRAID"]=HEALBOT_OPTIONS_COMBATPROT,
                        -- Skins Chat tab
                                 ["CHATNONE"]=HEALBOT_OPTIONS_CASTNOTIFY1,
                                 ["CHATSELF"]=HEALBOT_OPTIONS_CASTNOTIFY2,
                                 ["CHATTARGET"]=HEALBOT_OPTIONS_CASTNOTIFY3,
                                 ["CHATPARTY"]=HEALBOT_OPTIONS_CASTNOTIFY4,
                                 ["CHATRAID"]=HEALBOT_OPTIONS_CASTNOTIFY5,
                                 ["CHATCHAN"]=HEALBOT_OPTIONS_CASTNOTIFY6,
                                 ["CHATRESONLY"]=HEALBOT_OPTIONS_CASTNOTIFYRESONLY,
                                 ["CHATMSG"]=HEALBOT_OPTIONS_NOTIFY_MSG,
                                 ["EOCOOM"]=HEALBOT_OPTIONS_EOC_OOM,
                        -- Skins Frames General tab
                                 ["GOTOHEALGROUPS"]=HEALBOT_OPTIONS_SET_FRAME_HEALGROUPS,
                                 ["FRAMEALIAS"]=HEALBOT_OPTIONS_FRAME_ALIAS,
                                 ["FRAMELOCKED"]="Lock Frame",
                                 ["FRAMEAUTOSHOW"]=HEALBOT_OPTIONS_AUTOSHOW,
                                 ["FRAMEAUTOSHOWSOUND"]=HEALBOT_OPTIONS_PANELSOUNDS,
                                 ["FRAMEANCHOR"]=HEALBOT_OPTIONS_ANCHOR,
                                 ["BARANCHOR"]=HEALBOT_OPTIONS_BARSANCHOR,
                                 ["BARGROWDIRECTION"]=HEALBOT_OPTIONS_GROW_DIRECTION,
                                 ["BARORIENTATION"]=HEALBOT_OPTIONS_BARSORIENTATION,
                                 ["FRAMESCALE"]=HEALBOT_OPTIONS_FRAMESCALE,
                                 ["SFOFFSETH"]=HEALBOT_OPTIONS_STICKFRAMEOFFSETH,
                                 ["SFOFFSETV"]=HEALBOT_OPTIONS_STICKFRAMEOFFSETV,
                                 ["FRAMEBACKCOL"]="Frame Background",
                                 ["FRAMEBORDERCOL"]="Frame Border",
                                 ["TOOLTIPPOSITION"]=HEALBOT_OPTIONS_SETTOOLTIP_POSITION,
                        -- Skins Frames Heal Groups tab
                                 ["SELECTFRAMEFORGROUP"]=HEALBOT_OPTIONS_FRAME,
                                 ["ENABLEHEALGROUP"]=HEALBOT_OPTIONS_FRAME,
                                 ["HEALGROUPDOWN"]="Heal Group Down",
                                 ["HEALGROUPUP"]="Heal Group Up",
                                 ["HEALGROUPSALLOWDUPS"]=HEALBOT_ALLOW_DUPLICATES,
                        -- Skins Frames Headers Bars tab
                                 ["BARHEADERS"]="Bar Headers",
                                 ["HEADERBARSSHOW"]=HEALBOT_OPTIONS_SHOWHEADERS,
                                 ["HEADERBARSBARCOL"]="Header Bar Col"..HEALBOT_enWORD_COLOUR_SUFFIX..".",
                                 ["HEADERBARSTEXTCOL"]="Header Text Col"..HEALBOT_enWORD_COLOUR_SUFFIX..".",
                                 ["HEADERBARSTEXTURE"]=HEALBOT_OPTIONS_SKINTEXTURE,
                                 ["HEADERBARSHEIGHT"]=HEALBOT_OPTION_AGGROBAR.." "..HEALBOT_OPTIONS_SKINHEIGHT,
                                 ["HEADERBARSWIDTH"]=HEALBOT_OPTION_AGGROBAR.." "..HEALBOT_OPTIONS_SKINWIDTH,
                                 ["HEADERBARSFONTNAME"]=HEALBOT_OPTIONS_SKINFONT,
                                 ["HEADERBARSFONTHEIGHT"]=HEALBOT_OPTIONS_SKINFHEIGHT,
                                 ["HEADERBARSFONTOUTLINE"]=HEALBOT_OPTIONS_SKINFOUTLINE,
                                 ["HEADERBARSFONTOFFSET"]=HEALBOT_OPTIONS_FONT_OFFSET,
                        -- Skins Frames Headers Frames tab
                                 ["FRAMEHEADERS"]="Frame Headers",
                                 ["HEADERFRAMESTITLE"]=HEALBOT_OPTIONS_FRAME_TITLE,
                                 ["HEADERFRAMESSHOW"]=HEALBOT_OPTIONS_SHOWHEADERS,
                                 ["HEADERFRAMESBARCOL"]="Header Bar Col"..HEALBOT_enWORD_COLOUR_SUFFIX,
                                 ["HEADERFRAMESTEXTCOL"]="Header Text Col"..HEALBOT_enWORD_COLOUR_SUFFIX,
                                 ["HEADERFRAMESTEXTURE"]=HEALBOT_OPTIONS_SKINTEXTURE,
                                 ["HEADERFRAMESHEIGHT"]=HEALBOT_OPTION_AGGROBAR.." "..HEALBOT_OPTIONS_SKINHEIGHT,
                                 ["HEADERFRAMESWIDTH"]=HEALBOT_OPTION_AGGROBAR.." "..HEALBOT_OPTIONS_SKINWIDTH,
                                 ["HEADERFRAMESFONTNAME"]=HEALBOT_OPTIONS_SKINFONT,
                                 ["HEADERFRAMESFONTHEIGHT"]=HEALBOT_OPTIONS_SKINFHEIGHT,
                                 ["HEADERFRAMESFONTOUTLINE"]=HEALBOT_OPTIONS_SKINFOUTLINE,
                                 ["HEADERFRAMESFONTOFFSET"]=HEALBOT_OPTIONS_FONT_OFFSET,
                        -- Skins Frames Bars General tab
                                 ["BARSGENERAL"]="Bars General",
                                 ["HEALBARSTEXTURE"]=HEALBOT_OPTIONS_SKINTEXTURE,
                                 ["HEALBARSNUMCOLS"]=HEALBOT_OPTIONS_SKINNUMCOLS,
                                 ["HEALBARSGRPSPERCOLS"]=HEALBOT_OPTIONS_GROUPSPERCOLUMN,
                                 ["HEALBARSHEIGHT"]=HEALBOT_OPTION_AGGROBAR.." "..HEALBOT_OPTIONS_SKINHEIGHT,
                                 ["HEALBARSWIDTH"]=HEALBOT_OPTION_AGGROBAR.." "..HEALBOT_OPTIONS_SKINWIDTH,
                                 ["HEALBARSBRSPACE"]=HEALBOT_OPTIONS_SKINBRSPACE,
                                 ["HEALBARSBCSPACE"]=HEALBOT_OPTIONS_SKINBCSPACE,
                                 ["HEALBARSPOWERCOUNT"]=HEALBOT_OPTIONS_SHOWPOWERCOUNTER,
                                 ["HEALBARSLOWMANA"]=HEALBOT_OPTIONS_LOWMANAINDICATOR,
                                 ["HEALBARSLOWMANAIC"]=HEALBOT_OPTIONS_MONITORBUFFSC,
                        -- Skins Frames Bars Colours tab
                                 ["BARSCOLOUR"]="Bars Col"..HEALBOT_enWORD_COLOUR_SUFFIX.."s",
                                 ["HEALBARSCOLHEALTHTYPE"]=HEALBOT_SKIN_HEALTHBARCOL_TEXT,
                                 ["HEALBARSCOLHEALTH"]="Heal Bar Custom Col"..HEALBOT_enWORD_COLOUR_SUFFIX,
                                 ["HEALBARSCOLALPHA"]=HEALBOT_OPTIONS_BARALPHA,
                                 ["HEALBARSBACKCOLTYPE"]=HEALBOT_SKIN_HEALTHBACKCOL_TEXT,
                                 ["HEALBARSBACKCOL"]="Background Bar Custom Col"..HEALBOT_enWORD_COLOUR_SUFFIX,
                                 ["HEALBARSBACKOUTLINE"]=HEALBOT_OPTIONS_OUTLINE,
                                 ["HEALBARSBACKALPHA"]=HEALBOT_OPTIONS_BARALPHABACK,
                                 ["HEALBARSICCOLTYPE"]=HEALBOT_OPTIONS_INCHEAL,
                                 ["HEALBARSICCOL"]="Incoming Heals Custom Col"..HEALBOT_enWORD_COLOUR_SUFFIX,
                                 ["HEALBARSICALPHA"]=HEALBOT_OPTIONS_BARALPHAINHEAL,
                                 ["HEALBARSAECOLTYPE"]=HEALBOT_SKIN_ABSORBCOL_TEXT,
                                 ["HEALBARSAECOL"]=HEALBOT_classicABSORBHOTUP.." Effects Custom Col"..HEALBOT_enWORD_COLOUR_SUFFIX,
                                 ["HEALBARSAECOLALPHA"]=HEALBOT_OPTIONS_BARALPHAABSORB,
                                 ["HEALBARSALPHAOOR"]=HEALBOT_OPTIONS_BARALPHAEOR,
                                 ["HEALBARSALPHADIS"]=HEALBOT_OPTIONS_BARALPHADIS,
                        -- Skins Frames Bars Sort tab
                                 ["BARSSORT"]="Bars Sort",
                                 ["HEALBARSSORTSELF"]=HEALBOT_OPTIONS_SUBSORTSELFFIRST,
                                 ["HEALBARSSORTOOR"]=HEALBOT_OPTIONS_SORTOORLAST,
                                 ["HEALBARSSORTMAIN"]=HEALBOT_OPTIONS_MAINSORT,
                                 ["HEALBARSSORTSUB"]=HEALBOT_OPTIONS_SUBSORT,
                                 ["HEALBARSSELFPET"]=HEALBOT_OPTIONS_OWN_PET_WITH_SELF,
                                 ["HEALBARSPETGROUP"]=HEALBOT_OPTIONS_GROUP_PETS_BY_FIVE,
                        -- Skins Frames Bars Visibility tab
                                 ["BARSVISIBILITY"]="Bars Visibility",
                                 ["HEALBARSVISALERTIC"]=HEALBOT_OPTIONS_INCOMBATALERTLEVEL,
                                 ["HEALBARSVISALERTOC"]=HEALBOT_OPTIONS_OUTCOMBATALERTLEVEL,
                                 ["HEALBARSVISHIDE100"]=HEALBOT_HIDE_BARS,
                                 ["HEALBARSVISTARGETIC"]=HEALBOT_DISABLED_TARGET.." "..HEALBOT_OPTIONS_ENTERINGCOMBAT,
                                 ["HEALBARSVISFOCUSIC"]=HEALBOT_FOCUS.." "..HEALBOT_OPTIONS_ENTERINGCOMBAT,
                                 ["HEALBARSVISTARGETFRIEND"]=HEALBOT_OPTIONS_SHOW_ONLY_FRIEND,
                                 ["HEALBARSVISEXCLUDERAID"]=HEALBOT_OPTIONS_EXCLUDE_RAID,
                                 ["HEALBARSVISFOCUSFRIEND"]=HEALBOT_OPTIONS_SHOW_ONLY_FRIEND,
                                 ["HEALBARSVISFILTER"]=HEALBOT_OPTIONS_EMERGFILTER,
                                 ["HEALBARSVISFILTERGROUPS"]=HEALBOT_OPTIONS_EMERGFILTERGROUPS,
                                 ["HEALBARSVISENEMYINCSELF"]=HEALBOT_ENEMY_INCLUDE_SELF,
                                 ["HEALBARSVISENEMYINCTANKS"]=HEALBOT_ENEMY_INCLUDE_TANKS,
                                 ["HEALBARSVISENEMYINCARENA"]=HEALBOT_ENEMY_INCLUDE_ARENA,
                                 ["HEALBARSVISENEMYINCARENAPETS"]=HEALBOT_ENEMY_INCLUDE_ARENAPETS,
                                 ["HEALBARSVISENEMYINCMYTARGETS"]=HEALBOT_ENEMY_INCLUDE_MYTARGETS,
                                 ["HEALBARSVISENEMYNUMBOSSES"]=HEALBOT_ENEMY_NUMBER_BOSSES,
                                 ["HEALBARSVISENEMYHIDEOC"]=HEALBOT_ENEMY_HIDE_OUTOFCOMBAT,
                                 ["HEALBARSVISENEMYSHOWTARGET"]=HEALBOT_ENEMY_SHOW_TARGET,
                                 ["HEALBARSVISENEMYTARGETSIZE"]=HEALBOT_ENEMY_TARGET_SIZE,
                                 ["HEALBARSVISENEMYDOUBLEWIDTH"]=HEALBOT_ENEMY_DOUBLE_WIDTH,
                                 ["HEALBARSVISENEMYSHOWSELF"]=HEALBOT_ENEMY_EXISTS_SHOW_PTARGETS,
                                 ["HEALBARSVISENEMYSHOWARENA"]=HEALBOT_ENEMY_EXISTS_SHOW_ARENA,
                                 ["HEALBARSVISENEMYSHOWBOSSES"]=HEALBOT_ENEMY_EXISTS_SHOW_BOSSES,
                        -- Skins Frames Bars Aggro tab
                                 ["BARSAGGRO"]="Bars Aggro",
                                 ["HEALBARSAGGROSHOW"]=HEALBOT_OPTION_AGGROTRACK,
                                 ["HEALBARSAGGROSHOWTEXT"]=HEALBOT_OPTION_AGGROTXT,
                                 ["HEALBARSAGGROSHOWIND"]=HEALBOT_OPTION_AGGROIND,
                                 ["HEALBARSAGGROPCTTXT"]=HEALBOT_OPTION_AGGROPCTTRACK.." "..HEALBOT_OPTION_AGGROPCTTXT,
                                 ["HEALBARSAGGROINDALERT"]=HEALBOT_OPTIONS_AGGROINDALERT,
                                 ["HEALBARSAGGROBARALERT"]=HEALBOT_OPTIONS_AGGROALERT,
                        -- Skins Frames Bars Aux tab
                                 ["BARSAUX"]="Bars Aux",
                                 ["BARSAUXASSIGN"]=HEALBOT_OPTIONS_AUXASSIGN,
                                 ["BARSAUXOVERLAP"]=HEALBOT_OPTIONS_AUXOVERLAP,
                                 ["BARSAUXCONFIG"]=HEALBOT_OPTIONS_AUXINDCONFIG,
                                 ["BARSAUXCOLOUR"]="Auxiliary Bar Col"..HEALBOT_enWORD_COLOUR_SUFFIX,
                                 ["BARSAUXCOLOUROPACITYTYPE"]=HEALBOT_OPTIONS_AUXOPACITYTYPE,
                                 ["BARSAUXCUSTOMCOLOUR"]="Auxiliary Custom Col"..HEALBOT_enWORD_COLOUR_SUFFIX,
                                 ["BARSAUXANCHOR"]="Auxiliary Bar Anchor",
                                 ["BARSAUXSIZE"]="Auxiliary Bar Size",
                                 ["BARSAUXDEPTH"]="Auxiliary Bar Depth",
                                 ["BARSAUXOFFSET"]="Auxiliary Bar Offset",
                        -- Skins Frames Text Name tab
                                 ["TEXTNAME"]="Name Text",
                                 ["HEALBARSCOLTEXTNAME"]=HEALBOT_SKIN_NAMETEXTCOL_TEXT,
                                 ["HEALBARSCOLCUSTOMTEXTNAME"]="Name Text Custom Col"..HEALBOT_enWORD_COLOUR_SUFFIX,
                                 ["HEALBARSNAMETEXTCOLALPHA"]=HEALBOT_OPTIONS_BARALPHA,
                                 ["HEALBARSNAMETEXTDISCOLALPHA"]=HEALBOT_OPTIONS_BARALPHADIS,
                                 ["HEALBARSNAMETEXTDEBUFF"]=HEALBOT_OPTIONS_TEXTCOL_DEBUFF,
                                 ["HEALBARSTXTSHOWNAME"]=HEALBOT_OPTIONS_SHOWNAMEONBAR,
                                 ["HEALBARSTXTUTF8"]=HEALBOT_OPTIONS_ENABLELIBUTF8,
                                 ["HEALBARSTXTSHOWCLASS"]=HEALBOT_OPTIONS_SHOWCLASSONBAR,
                                 ["HEALBARSTXTSHOWROLE"]=HEALBOT_SHOW_ROLE,
                                 ["HEALBARSTXTSHOWCLASSICON"]=HEALBOT_SHOW_CLASS_AS_ICON,
                                 ["HEALBARSTXTSHOWCLASSTEXT"]=HEALBOT_SHOW_CLASS_AS_TEXT,
                                 ["HEALBARSTXTTAGDC"]=HEALBOT_DISCONNECTED_LABEL.." Tag",
                                 ["HEALBARSTXTTAGRIP"]=HEALBOT_DEAD_LABEL.." Tag",
                                 ["HEALBARSTXTTAGOOR"]=HEALBOT_OUTOFRANGE_LABEL.." Tag",
                                 ["HEALBARSTXTTAGR"]=HEALBOT_RESERVED_LABEL.." Tag",
                                 ["HEALBARSTXTFONT"]=HEALBOT_OPTIONS_SKINFONT,
                                 ["HEALBARSTXTFONTHEIGHT"]=HEALBOT_OPTIONS_SKINFHEIGHT,
                                 ["HEALBARSTXTFONTOFFSET"]=HEALBOT_OPTIONS_FONT_OFFSET,
                                 ["HEALBARSTXTFONTHOFFSET"]=HEALBOT_OPTIONS_FONT_OFFSET,
                                 ["HEALBARSTXTFONTALIGN"]=HEALBOT_OPTIONS_TEXTALIGNMENT,
                                 ["HEALBARSTXTFONTOUTLINE"]=HEALBOT_OPTIONS_SKINFOUTLINE,
                                 ["HEALBARSTXTMAXCHARS"]=HEALBOT_OPTIONS_MAXCHARS,
                        -- Skins Frames Text Health tab
                                 ["TEXTHEALTH"]="Health Text",
                                 ["HEALBARSCOLTEXTHEALTH"]=HEALBOT_SKIN_NAMETEXTCOL_TEXT,
                                 ["HEALBARSCOLCUSTOMTEXTHEALTH"]="Health Text Custom Col"..HEALBOT_enWORD_COLOUR_SUFFIX,
                                 ["HEALBARSHEALTHTEXTCOLALPHA"]=HEALBOT_OPTIONS_BARALPHA,
                                 ["HEALBARSHEALTHTEXTDISCOLALPHA"]=HEALBOT_OPTIONS_BARALPHADIS,
                                 ["HEALBARSTXTSHOWHEALTH"]=HEALBOT_OPTIONS_SHOWHEALTHONBAR,
                                 ["HEALBARSTXTHEALTHICOPTION"]="Incoming Heals Options",
                                 ["HEALBARSTXTHEALTHICAOPTION"]="Incoming "..HEALBOT_classicABSORBHOT.."s Options",
                                 ["HEALBARSTXTHEALTHSOHEALS"]="Overhealing Options",
                                 ["HEALBARSTXTHLTHANCHOR"]=HEALBOT_OPTIONS_HEALTHTEXTANCHOR,
                                 ["HEALBARSTXTIGNOREINFULL"]=HEALBOT_OPTIONS_IGNOREINCOMINGONFULL,
                                 ["HEALBARSTXTHEALTHTYPE"]="Display Type",
                                 ["HEALBARSTXTHEALTHFORMAT"]="Format Dropdowns",
						-- Skins Frames Icons  tab
								 ["ICONSDEBUFFS"]="Icons Debuffs",
								 ["ICONSBUFFS"]="Icons Buffs",
								 ["ICONSEXTRA"]="Icons Extras",
							     ["ICONPOSITION"]=HEALBOT_OPTIONS_ICONPOSITION,
							     ["ICONANCHOR"]=HEALBOT_OPTIONS_ICONANCHOR,
                        -- Skins Frames Icons Aura General tab
                                 ["ICONSDEBUFFGENERAL"]="Icons Debuffs General",
							     ["ICONSBUFFGENERAL"]="Icons Buffs General",
                                 ["ICONNUMHOT"]=HEALBOT_OPTIONS_ALLSPELLS.." "..HEALBOT_OPTIONS_MAXICONS,
                                 ["ICONSHOWDEBUFF"]=HEALBOT_OPTIONS_SHOWDEBUFFICON,
                                 ["ICONNUMDEBUFF"]=HEALBOT_OPTIONS_TAB_DEBUFFS.." "..HEALBOT_OPTIONS_MAXICONS,
                                 ["ICONDOUBLE"]=HEALBOT_OPTIONS_DOUBLEROW,
                                 ["ICONSCALE"]=HEALBOT_OPTIONS_ICONSCALE,
                                 ["ICONALWAYSEN"]=HEALBOT_OPTIONS_TTALPHA.." "..HEALBOT_OPTIONS_ENABLEHEALTHY,
                                 ["ICONFADE"]=HEALBOT_OPTIONS_FADEONEXPIRE,
                                 ["ICONFADESTART"]=HEALBOT_OPTIONS_FADESTARTTIME,
                        -- Skins Frames Icons Aura Text tab
                                 ["ICONSDEBUFFTEXT"]="Icons Debuffs Text",
						         ["ICONSBUFFTEXT"]="Icons Buffs Text",
                                 ["ICONTXTSHOWCOUNT"]=HEALBOT_OPTIONS_HOTSHOWTEXT.." "..HEALBOT_OPTIONS_HOTTEXTCOUNT,
                                 ["ICONTXTSHOWDUR"]=HEALBOT_OPTIONS_HOTSHOWTEXT.." "..HEALBOT_OPTIONS_HOTTEXTDURATION,
                                 ["ICONTXTDURTIME"]=HEALBOT_OPTIONS_SHOWDURATIONFROM,
                                 ["ICONTXTDURWARNTIME"]=HEALBOT_OPTIONS_SHOWDURATIONWARN,
                                 ["ICONTXTFONT"]=HEALBOT_OPTIONS_SKINFONT,
                                 ["ICONTXTFONTSIZE"]=HEALBOT_OPTIONS_SKINFHEIGHT,
                                 ["ICONTXTFONTOUTLINE"]=HEALBOT_OPTIONS_SKINFOUTLINE,
                        -- Skins Frames Icons Extra tabs
						         ["ICONSCLASSROLE"]="Icons Extras Class / Role",
						         ["ICONSRAIDTARGET"]="Icons Extras Raid Target",
						         ["ICONSREADYCHECK"]="Icons Extras Ready Check",
						         ["ICONSOORARROW"]="Icons Extras Out of Range Arrow.",
                                 ["ICONSHOWRC"]=HEALBOT_OPTIONS_SHOWREADYCHECK,
                                 ["ICONSHOWCLASS"]=HEALBOT_OPTIONS_SHOWCLASSICON,
                                 ["ICONSHOWRT"]=HEALBOT_OPTIONS_BARBUTTONSHOWRAIDICON,
                                 ["ICONSHOWDIR"]=HEALBOT_OPTIONS_SHOWDIRECTION,
                                 ["ICONSHOWDIRMO"]=HEALBOT_OPTIONS_SHOWDIRECTIONMOUSE,
								 ["ICONOFFSET"]="Extra Icon Offset",
                        -- Debuffs General tab
                                 ["MONITORDEBUFFS"]=HEALBOT_OPTIONS_MONITORDEBUFFS,
                                 ["MONITORDEBUFFSIC"]=HEALBOT_OPTIONS_MONITORBUFFSC,
                                 ["MONITORDEBUFFSGROUPED"]=HEALBOT_OPTIONS_IN_A_GROUP,
                                 ["DEBUFFSSPELLTOCURE"]=HEALBOT_OPTIONS_DEBUFFTEXT1,
                                 ["DEBUFFSSPELLCHECKMEMBERS"]=HEALBOT_OPTIONS_BUFFSTEXT2,
                                 ["DEBUFFSIGNOREDEBUFFS"]="Ignore Debuffs",
                                 ["DEBUFFSTYPEPRIORITY"]=HEALBOT_WORD_PRIORITY,
                                 ["DEBUFFSTYPECOLOUR"]=HEALBOT_OPTIONS_BUFFSTEXT3,
                        -- Debuffs Custom tab
                                 ["DEBUFFSCUSTOMCAT"]=HEALBOT_CUSTOM_CATEGORY,
                                 ["DEBUFFSCUSTOMDEBUFF"]=HEALBOT_OPTIONS_TAB_CUSTOM_DEBUFFS,
                                 ["DEBUFFSCUSTOMIDMETHOD"]=HEALBOT_OPTIONS_CUSTOM_IDMETHOD,
                                 ["DEBUFFSCUSTOMCASTBY"]=HEALBOT_OPTIONS_CUSTOM_CASTBY,
                                 ["DEBUFFSCUSTOMDELETE"]=HEALBOT_OPTIONS_DELSKIN,
                                 ["DEBUFFSCUSTOMNEWNAME"]=HEALBOT_OPTIONS_NEWDEBUFFTEXT,
                                 ["DEBUFFSCUSTOMNEWSAVE"]=HEALBOT_OPTIONS_SAVESKIN,
                                 ["DEBUFFSCUSTOMENDIS"]=HEALBOT_WORD_DISABLE,
                                 ["DEBUFFSCUSTOMPRIORITY"]=HEALBOT_WORD_PRIORITY,
                                 ["DEBUFFSCUSTOMCOLOUR"]=HEALBOT_SKIN_HEADERBARCOL,
                                 ["DEBUFFSCUSTOMCOLOURSHOW"]=HEALBOT_SKIN_HEADERBARCOL,
                                 ["DEBUFFSCUSTOMRESET"]=HEALBOT_WORD_RESET,
                                 ["DEBUFFSCUSTOMPAGE"]="Page",
                                 ["DEBUFFSCUSTOMALLDISEASE"]=HEALBOT_OPTIONS_CUSTOM_ALLDISEASE,
                                 ["DEBUFFSCUSTOMALLMAGIC"]=HEALBOT_OPTIONS_CUSTOM_ALLMAGIC,
                                 ["DEBUFFSCUSTOMALLPOISON"]=HEALBOT_OPTIONS_CUSTOM_ALLPOISON,
                                 ["DEBUFFSCUSTOMALLCURSE"]=HEALBOT_OPTIONS_CUSTOM_ALLCURSE,
                                 ["DEBUFFSCUSTOMALLBOSS"]=HEALBOT_OPTIONS_CUSTOM_ALLBOSS,
                                 ["DEBUFFSCUSTOMALLTIMED"]=HEALBOT_OPTIONS_CUSTOM_ALLTIMED,
                        -- Debuffs Warning tab
                                 ["DEBUFFSWARNINGBAR"]=HEALBOT_OPTIONS_CDCSHOWHBARS,
                                 ["DEBUFFSWARNINGBARRANGE"]="Range",
                                 ["DEBUFFSWARNINGSHOW"]=HEALBOT_OPTIONS_SHOWDEBUFFWARNING,
                                 ["DEBUFFSWARNINGSHOWRANGE"]="Range",
                                 ["DEBUFFSWARNINGSOUND"]=HEALBOT_OPTIONS_SOUNDDEBUFFWARNING,
                                 ["DEBUFFSWARNINGSOUNDRANGE"]="Range",
                                 ["DEBUFFSWARNINGSOUNDSELECT"]=HEALBOT_OPTIONS_SOUND,
                                 ["DEBUFFSWARNINGSOUNDPREVIEW"]=HEALBOT_OPTIONS_SOUND,
								 ["DEBUFFSWARNINGSPAMFILTER"]=HEALBOT_OPTIONS_SPAMFILTER,
                        -- Buffs General tab
                                 ["MONITORBUFFS"]=HEALBOT_OPTIONS_MONITORBUFFS,
                                 ["MONITORBUFFSIC"]=HEALBOT_OPTIONS_MONITORBUFFSC,
                                 ["MONITORBUFFSGROUPED"]=HEALBOT_OPTIONS_IN_A_GROUP,
                                 ["MONITORBUFFSPALABLESSING"]=HEALBOT_OPTIONS_PALADIN_BLESSINGS,
                                 ["BUFFSSPELL"]=HEALBOT_OPTIONS_BUFFSTEXT1,
                                 ["BUFFSMEMBERS"]=HEALBOT_OPTIONS_BUFFSTEXT2,
                                 ["BUFFSBARS"]=HEALBOT_OPTIONS_CDCBARS,
                                 ["BUFFSTIMER"]=HEALBOT_OPTIONS_BUFFSTEXTTIMER,
                        -- Buffs Custom tab
                                 ["BUFFSCUSTOMCAT"]=HEALBOT_CUSTOM_CATEGORY,
                                 ["BUFFSCUSTOMBUFF"]=HEALBOT_OPTIONS_ALLSPELLS,
                                 ["BUFFSCUSTOMIDMETHOD"]=HEALBOT_OPTIONS_CUSTOM_IDMETHOD,
                                 ["BUFFSCUSTOMCASTBY"]=HEALBOT_OPTIONS_CUSTOM_CASTBY,
                                 ["BUFFSCUSTOMDELETE"]=HEALBOT_OPTIONS_DELSKIN,
                                 ["BUFFSCUSTOMNEWNAME"]=HEALBOT_OPTIONS_NEWHOTBUFFTEXT,
                                 ["BUFFSCUSTOMNEWSAVE"]=HEALBOT_OPTIONS_SAVESKIN,
                                 ["BUFFSCUSTOMENDIS"]=HEALBOT_WORD_DISABLE,
                                 ["BUFFSCUSTOMPRIORITY"]=HEALBOT_WORD_PRIORITY,
                                 ["BUFFSCUSTOMCOLOUR"]=HEALBOT_SKIN_HEADERBARCOL,
                                 ["BUFFSCUSTOMCOLOURSHOW"]=HEALBOT_SKIN_HEADERBARCOL,
                                 ["BUFFSCUSTOMRESET"]=HEALBOT_WORD_RESET,
                                 ["BUFFSCUSTOMPAGE"]="Page",
                        -- Buffs Warning tab
                                 ["BUFFSWARNINGBAR"]=HEALBOT_OPTIONS_CDCSHOWHBARS,
                                 ["BUFFSWARNINGBARRANGE"]="Range",
                                 ["BUFFSWARNINGSHOW"]=HEALBOT_OPTIONS_SHOWBUFFWARNING,
                                 ["BUFFSWARNINGSHOWRANGE"]="Range",
                                 ["BUFFSWARNINGSOUND"]=HEALBOT_OPTIONS_SOUNDBUFFWARNING,
                                 ["BUFFSWARNINGSOUNDRANGE"]="Range",
                                 ["BUFFSWARNINGSOUNDSELECT"]=HEALBOT_OPTIONS_SOUND,
                                 ["BUFFSWARNINGSOUNDPREVIEW"]=HEALBOT_OPTIONS_SOUND,
                        -- Tips tab
                                 ["TOOLTIPSHOW"]=HEALBOT_OPTIONS_SHOWTOOLTIP,
                                 ["TOOLTIPHIDEIC"]=HEALBOT_OPTIONS_DISABLETOOLTIPINCOMBAT,
                                 ["TOOLTIPTARGETINFO"]=HEALBOT_OPTIONS_SHOWUNITTOOLTIP,
                                 ["TOOLTIPMYBUFFS"]=HEALBOT_OPTIONS_SHOWUNITBUFFTIME,
                                 ["TOOLTIPSPELLDETAIL"]=HEALBOT_OPTIONS_SHOWDETTOOLTIP,
                                 ["TOOLTIPSPELLCD"]=HEALBOT_OPTIONS_SHOWCDTOOLTIP,
                                 ["TOOLTIPIGNORESPELLGCD"]=HEALBOT_OPTIONS_IGNOREGCDTOOLTIP,
                                 ["TOOLTIPWHEELCMD"]=HEALBOT_OPTIONS_SHOWMOUSEWHEELTOOLTIP,
                                 ["TOOLTIPHOTREC"]=HEALBOT_OPTIONS_SHOWRECTOOLTIP,
                                 ["TOOLTIPGAMETIP"]=HEALBOT_OPTIONS_USEGAMETOOLTIP,
                                 ["TOOLTIPMONBUFFS"]=HEALBOT_OPTIONS_TOOLTIPSHOWHOT,
                                 ["TOOLTIPFONTSIZE"]=HEALBOT_OPTIONS_SKINFHEIGHT,
                                 ["TOOLTIPPOSITIONLINK"]=HEALBOT_OPTIONS_SETTOOLTIP_POSITION,
                                 ["TOOLTIPALPHA"]=HEALBOT_OPTIONS_TTALPHA,
                        -- Mouse Wheel tab
                                 ["BUFFSMOUSEWHEELUSE"]=HEALBOT_OPTIONS_MOUSEWHEEL,
                                 ["BUFFSMOUSEWHEELCMD"]="Mouse Wheel Commands",
                                 ["BUFFSMOUSEWHEELEMOTE"]="Mouse Wheel Emotes",
                        -- Test tab
                                 ["TESTUSE"]=HEALBOT_OPTIONS_TESTBARS,
                                 ["TESTPROFILE"]=HEALBOT_WORDS_PROFILE,
                                 ["TESTNUMTOTAL"]=HEALBOT_OPTION_NUMBARS,
                                 ["TESTNUMTANKS"]=HEALBOT_OPTION_NUMTANKS,
                                 ["TESTNUMHEALS"]=HEALBOT_OPTION_NUMHEALERS,
                                 ["TESTNUMMYTARGETS"]=HEALBOT_OPTION_NUMMYTARGETS,
                                 ["TESTNUMPETS"]=HEALBOT_OPTION_NUMPETS,
                                 ["TESTNUMENEMY"]=HEALBOT_OPTION_NUMENEMYS,
                        -- Import/Export tab
                                 ["INOUTSKINS"]="Import/Export Skins tab.",
                                 ["INOUTCUSTOMDEBUFFS"]="Import/Export Custom Debuffs tab.",
                                 ["INOUTCUSTOMBUFFS"]="Import/Export Custom Buffs tab.",
                                 ["INOUTSPELLS"]="Import/Export Spells tab.",
                                 ["INOUTPRESETCOLS"]="Import/Export Preset Col"..HEALBOT_enWORD_COLOUR_SUFFIX.."s tab.",
                        -- Import/Export Skins tab
                                 ["INOUTSELECTSKIN"]=HEALBOT_OPTIONS_EXPORTSKIN,
                                 ["INEXTRASKIN"]=HEALBOT_OPTIONS_EXTRASKINS,
                                 ["INOUTEXPORTSKIN"]=HEALBOT_OPTIONS_BUTTONEXPORT,
                                 ["INOUTIMPORTSKIN"]=HEALBOT_OPTIONS_BUTTONIMPORT,
                        -- Import/Export Custom Debuffs tab
                                 ["INOUTEXPORTCDEBUFF"]=HEALBOT_OPTIONS_BUTTONEXPORT,
                                 ["INOUTIMPORTCDEBUFFMETHOD"]=HEALBOT_OPTIONS_BUTTONIMPORTMETHOD,
                                 ["INOUTIMPORTCDEBUFF"]=HEALBOT_OPTIONS_BUTTONIMPORT,
                        -- Import/Export Custom Buffs tab
                                 ["INOUTEXPORTCBUFF"]=HEALBOT_OPTIONS_BUTTONEXPORT,
                                 ["INOUTIMPORTCBUFFMETHOD"]=HEALBOT_OPTIONS_BUTTONIMPORTMETHOD,
                                 ["INOUTIMPORTCBUFF"]=HEALBOT_OPTIONS_BUTTONIMPORT,
                        -- Import/Export Spells tab
                                 ["INOUTEXPORTSPELLS"]=HEALBOT_OPTIONS_BUTTONEXPORT,
                                 ["INOUTIMPORTSPELLSMETHOD"]=HEALBOT_OPTIONS_BUTTONIMPORTMETHOD,
                                 ["INOUTIMPORTSPELLS"]=HEALBOT_OPTIONS_BUTTONIMPORT,
                        -- Import/Export Preset Colours tab
                                 ["INOUTEXPORTPRESETCOLS"]=HEALBOT_OPTIONS_BUTTONEXPORT,
                                 ["INOUTIMPORTPRESETCOLS"]=HEALBOT_OPTIONS_BUTTONIMPORT,
                              }
    HEALBOT_OPTIONS_HELP_TEXT={
                        -- Preset Colours
                               ["PRESETCOLS"]="Select a Prefix Col"..HEALBOT_enWORD_COLOUR_SUFFIX..".\nUp to 10 Prefix Col"..HEALBOT_enWORD_COLOUR_SUFFIX.."s can be defined.",
                               ["PRESETCOLALIAS"]="Set a meaningful name for the Prefix Col"..HEALBOT_enWORD_COLOUR_SUFFIX..".",
                               ["PRESETCOLSET"]="Click to set the Preset Col"..HEALBOT_enWORD_COLOUR_SUFFIX..".",
                               ["PRESETCOLSELECT"]="Click to select the Preset Col"..HEALBOT_enWORD_COLOUR_SUFFIX..".",
                               ["PRESETCOLCANCEL"]="Click to leave without selecting a Preset Col"..HEALBOT_enWORD_COLOUR_SUFFIX..".",
                        -- General tab
                               ["HIDEOPTIONBUTTON"]="Hide the options button that is\nshown at the bottom of the 1st frame.",
                               ["RIGHTTOOPENOPTIONS"]="Right click on the edge of\na frame will open options.",
                               ["SHOWMINIMAPBUTTON"]="Show a button on the minimap\nthat will open options.",
                               ["QUERYTALENTS"]="Query talent information when\nthe mouse moves over a bar.\nNOTE: This is only used by tooltips.",
                               ["ENABLEAUTOCOMBAT"]="Put healbot into lockdown combat mode when\nanyone in the group/raid goes into combat.",
                               ["ENABLEFASTHEALTH"]="Monitor combat log for instant health updates.\nNOTE: Not recommended in retail.",
                               ["IGNOREAURAEVENTS"]="Ignore required buffs when resting.",
                               ["DISABLEHEALBOT"]="Put Healbot into a deep sleep.",
                               ["DISABLEHEALBOTSOLO"]="Healbot is only sleeping when\nnot in a group or raid.",
                               ["ADJUSTMAXHLTH"]="Check for boss debuffs that alters healing\neffects and adjust max health to reflect.",
                               ["OPTIONSOPACITY"]="Set the opaticy of the option panels.",
                               ["INTERNALTIMERS"]="This combined with your FPS sets how quickly the following are updated:\n- Range checking\n- Buff updates\n- Debuff updates\n- Aggro updates\n- Enemy bar updates\n- Fluid bars update frequency\n- Aggro bars flash frequency\n- General checks and out of combat updates\n--\nNote: Higher settings use significantly more CPU.",
                               ["LANG"]="Select the language used by healbot options.\nThis can be independent to the UI.",
                               ["SETLANG"]="Set the language selected.",
                               ["CMDS"]="Select a command to run.\nMany commands allow for resetting parts of\nhealbot without the need to reset to defaults.",
                               ["RUNCMDS"]="Run the command selected.",
                               ["PROFILE"]="Select to use Class or Character for saving\nsettings related to Spells, Buffs and Debuffs.",
                               ["SETPROFILE"]="Set the profile selected.",
							   ["OPTTHEME"]="Set the options Title Box, Borders and Contents text Col"..HEALBOT_enWORD_COLOUR_SUFFIX..".",
                               ["CLASSTYPES"]="Classes can be grouped as Melee, Ranged, Healers and Custom.\nGroups of classes are available in options:\n- Bars Visibility\n- General Debuffs\n- General Buffs\n--\nThese settings date back to Classic and have little use in today's WoW.\nThey have near zero overhead and so are kept as some might find them useful.",
                        -- Overrides tab
                               ["OVERRIDESEFFECTS"]="Show the Overrides Effects tab.",
                               ["OVERRIDESPROT"]="Show the Overrides Protection tab.",
                               ["OVERRIDESCHAT"]="Show the Overrides Chat tab.",
                               ["OVERRIDESFRAMES"]="Show the Overrides Frames tab.",
                               ["OVERRIDESEFFECTSUSE"]="Select to use the skin settings or\nalways override with settings on this tab.",
                        -- Spells tab
                               ["SETSPELLSFOR"]="Set spells that can be used in different states:\n* Enabled - Always when in combat and any time the bar is in an enabled state.\n* Disabled - Only when out of combat and the bar is in a disabled state.\n* Enemy - Allows for harmful spells to be set and used on enemy bars.",
                               ["ALWAYSUSEENABLED"]="Use this option to always cast enabled\nspells regardless of the bar state.",
                               ["SPELLSBUTTON"]="The button press to cast a spell.",
                               ["SPELLSBUTTONCAST"]="Timing of the spell cast\nCast when the button is Pressed or Released.",
                               ["SPELLSAVOIDBLUE"]="Cast Binding Heal on yourself and ended up\nwith a blue cursor? this option is your friend.",
                               ["SPELLSAUTOTARGET"]="Set the healers target to the player/npc\nreceiving the current spell cast.",
                               ["SPELLSAUTOTRINKET"]="Attempt to use trinkets automatically when casting spells.\n-------------\nWARNING\n-------------\nSome trinkets break the cast using this method\nensure the trinket works with the spell selected.",
                               ["SPELLSBUTTONCLICK"]="Spell to cast on button click.",
                               ["SPELLSBUTTONSHIFTCLICK"]="Spell to cast on button click\nwith the SHIFT key held down.",
                               ["SPELLSBUTTONCTRLCLICK"]="Spell to cast on button click\nwith the CTRL key held down.",
                               ["SPELLSBUTTONALTCLICK"]="Spell to cast on button click\nwith the ALT key held down.",
                               ["SPELLSBUTTONSHIFTCTRLCLICK"]="Spell to cast on button click with\nthe SHIFT and CTRL key held down.",
                               ["SPELLSBUTTONSHIFTALTCLICK"]="Spell to cast on button click with\nthe SHIFT and ALT key held down.",
                               ["SPELLSBUTTONCTRLALTCLICK"]="Spell to cast on button click with\nthe CTRL and ALT key held down.",
                               ["SPELLSHELPSELECT"]="Displays dropdowns for selecting various\nspells, macros and other commands.",
                               ["SPELLSSELECTSPELL"]="Select a spell for the spells tab.",
                               ["SPELLSSELECTMACRO"]="Select a macro for the spells tab.",
                               ["SPELLSSELECTITEMS"]="Select an item for the spells tab.",
                               ["SPELLSSELECTCMDS"]="Select a command for the spells tab.",
                               ["SPELLSSELECTCANCEL"]="Do not select anything and\nreturn to the spells tab.",
                               ["SMARTCAST"]="Select and cast an appropriate spell for the situation.\nThis only works out of combat.",
                               ["SMARTCASTAVOIDPVP"]="Do not use SmartCast\non PVP flagged players.",
                               ["SMARTCASTDEBUFF"]="Use SmartCast to remove debuffs.",
                               ["SMARTCASTBUFF"]="Use SmartCast to apply buffs.",
                               ["SMARTCASTHEAL"]="Use SmartCast to cast healing type spells.",
                               ["SMARTCASTRES"]="Use SmartCast to cast resurrection type spells.",
                        -- Skins top
                               ["SELECTSKIN"]="Select the skin you want to use.",
                               ["DELSKIN"]="Delete the current skin.\nNote: The standard skin cannot be deleted.",
                               ["NEWSKIN"]="Enter a name for a new skin that will\nbe based on the currently selected skin.",
                               ["SAVENEWSKIN"]="Create a new skin based on the currently selected skin.",
                               ["SELECTFRAME"]="Select from a list of 10 frames.\nFrame options will be displayed and\ncan be updated for the current selected frame",
                               ["FRAMEAPPLYTAB"]="An easy way to set the current tab options to all frames.",
                        -- Skins General tab
                               ["SKINDEFAULTFOR"]="Set when the skin is displayed.\nNote: This setting is Per Character.",
                               ["STICKFRAMES"]="When turned on a frame will stick to\nanother frame higher up in the list.\nLocked frames will remain stuck.\nUnlocked frames can be moved away.\n--\nTIP: Use the 1st frame as your main frame\nmove other frames to your main frame\nand when stuck lock them.",
                               ["STICKSENSITIVITY"]="The higher the sensitivity the closer you need to get for a frame to stick to another frame.\n--\nTIP: Use test bars to see if the sensitivity is correct for your frames.\nTurn On/Off/On test bars to see if the frames remain in place.\n- High sensitivity can lead to frames becoming unstuck on reload/logon\n- Low sensitivity can lead to a frame attaching to a different frame on reload/logon\n* Start with a high sensitivity and lower if required.",
                               ["HIDEBLIZPARTYFRAMES"]="Hide the standard Blizzard party frames\noptionally include the player and pet frames.\nNote: Changing this setting requires a UI Reload.",
                               ["HIDEBLIZBOSSFRAMES"]="Hide the standard Blizzard boss frames.\nNote: Changing this setting requires a UI Reload.",
                               ["HIDEBLIZRAIDFRAMES"]="Hide the standard Blizzard raid frames.\nNote: Changing this setting requires a UI Reload.",
                        -- Skins Effects tab
                               ["USEFLUIDBARS"]="Bar updates due to health changes are done in a fluid motion.",
                               ["FLUIDBARSREFRESHSPEED"]="Controls how fast the bar updates.\nSlower is smoother as Faster skips steps.\nTIP: For a smooth yet fast fluid update:\nFirst increase Internal Timers and Updates on the General tab.",
                               ["HEALBARSAGGROBARFLASHFREQ"]="Set the speed the aux bars flash.\nNote: faster means skipping steps in the update.\nFor a faster and smoother update first increase Internal Timers and Updates on the General Tab.",
                               ["HEALBARSAGGROBARFLASHMIN"]="To give the effect of flashing, aux bars increase and decrease transparency in steps.\nMin - The minimum opacity.",
                               ["HEALBARSAGGROBARFLASHMAX"]="To give the effect of flashing, aux bars increase and decrease transparency in steps.\nMax - The maximum opacity.",
                        -- Skins Protection tab
                               ["USECRASHPROT"]="Crash protection guards against the negative\neffects of a healbot user disconnecting during combat.\nA small number of macro slots will store current\ngroup/raid data that can be used on logon during combat.",
                               ["USECRASHPROTGENERALMACRO"]="Use global macro slots rather than per character.\nTo reduce overall usage this option is recommended\nwhen using Healbot on multiple characters.",
                               ["USECRASHPROTBASEMACRO"]="Set a common text string to be\nused at the start of the macro names.",
                               ["USECRASHPROTLOGONDURATION"]="Set how long protection data is valid after logon.",
                               ["USECOMBATPROT"]="Combat protection reserves bars to guard against random\nmembers leaving/joining the group/raid during combat.\nThis option will reserve bars to make up\nthe numbers to standard group or raid sizes.",
                               ["USECOMBATPROTGROUP"]="Use Combat Protection in Groups.",
                               ["USECOMBATPROTRAID"]="Use Combat Protection in Raids.",
                        -- Skins Chat tab
                               ["CHATNONE"]="Do not send chat messages.",
                               ["CHATSELF"]="Send chat messages only to yourself, good for testing.",
                               ["CHATTARGET"]="Send whisper to the target.",
                               ["CHATPARTY"]="Send chat message to the group channel.",
                               ["CHATRAID"]="Send chat message to the raid channel.",
                               ["CHATCHAN"]="Send chat message to your own general channel.",
                               ["CHATRESONLY"]="Send chat messages only when casting resurrection type spells.",
                               ["CHATMSG"]="The format of the message to send.\n#s is substituted with the spell name.\n#n is substituted with the players name.",
                               ["EOCOOM"]="When enabled and mana drops below the select amount.\nAt the end of combat emote Out of Mana.",
                        -- Skins Frames General tab
                               ["GOTOHEALGROUPS"]="Go to the Heal Groups tab.",
                               ["FRAMEALIAS"]="Give the frame a meaningful alias.\nAliases are shown on the Heal Groups tab",
                               ["FRAMELOCKED"]="Lock the frame at the current position.\nNote: If the frame is locked and stuck to another frame\nthe frame will remain stuck and cannot be unstuck.",
                               ["FRAMEAUTOSHOW"]="Hide the frame when out of combat and\nnone of the bars are in an enabled state.",
                               ["FRAMEAUTOSHOWSOUND"]="Play a bell sound when opening the frame.",
                               ["FRAMEANCHOR"]="The position of the frame anchor relative to the screen.\nNote: When the frame is stuck to another frame\nthis setting is automatically updated\nand used to store the frames location.",
                               ["BARANCHOR"]="The position of the bars anchor relative to the frame.",
                               ["BARGROWDIRECTION"]="The direction the bars grow away from the bars anchor.",
                               ["BARORIENTATION"]="The direction each bar will shrink/grow depending on the players health.",
                               ["FRAMESCALE"]="The scale of the current frame.",
                               ["SFOFFSETH"]="Set the horizontal offset of this frame\nwhen this frame is stuck to another frame.",
                               ["SFOFFSETV"]="Set the vertical offset of this frame\nwhen this frame is stuck to another frame.",
                               ["FRAMEBACKCOL"]="Set the background col"..HEALBOT_enWORD_COLOUR_SUFFIX.." for the frame.",
                               ["FRAMEBORDERCOL"]="Set the border for the frame.",
                               ["TOOLTIPPOSITION"]="The location of the tooltip relative to the frame.",
                        -- Skins Frames Heal Groups tab
                               ["SELECTFRAMEFORGROUP"]="Select a frame for the group.",
                               ["ENABLEHEALGROUP"]="Include/Exclude the heal group.",
                               ["HEALGROUPDOWN"]="Move the heal group down.\nHeal Groups sharing frames are initially\nsorted by the order of this list.",
                               ["HEALGROUPUP"]="Move the heal group up.\nHeal Groups sharing frames are initially\nsorted by the order of this list.",
                               ["HEALGROUPSALLOWDUPS"]="Allow a duplicate bar in the Raid/Group/Pets Heal Group\nwhen a bar exists in the Tank/Healers/Self/Private List Heal Group.",
                        -- Skins Frames Headers Bars tab
                               ["BARHEADERS"]="Show the Skins Frames Headers Bars tab.",
                               ["HEADERBARSSHOW"]="Turn On/Off displaying the bars headers.\n- For the raid heal group the header is based on main sort.\n- For other heal groups the header is the heal group name.",
                               ["HEADERBARSBARCOL"]="Set the bar col"..HEALBOT_enWORD_COLOUR_SUFFIX.." for the header bars.",
                               ["HEADERBARSTEXTCOL"]="Set the text col"..HEALBOT_enWORD_COLOUR_SUFFIX.." shown on the header bars.",
                               ["HEADERBARSTEXTURE"]="Set the texture for the header bars.",
                               ["HEADERBARSHEIGHT"]="Set the height for the header bars.",
                               ["HEADERBARSWIDTH"]="Set the width for the header bars.\nThis is based on the bars width.",
                               ["HEADERBARSFONTNAME"]="Set the font for the text\ndisplayed on the header bars.",
                               ["HEADERBARSFONTHEIGHT"]="Set the font size for the text\ndisplayed on the header bars.",
                               ["HEADERBARSFONTOUTLINE"]="Set the font outline for the text\ndisplayed on the header bars.",
                               ["HEADERBARSFONTOFFSET"]="Vertically offset the header text.",
                        -- Skins Frames Headers Frames tab
                               ["FRAMEHEADERS"]="Show the Skins Frames Headers Frames tab.",
                               ["HEADERFRAMESTITLE"]="Set the text to be displayed for the frame.",
                               ["HEADERFRAMESSHOW"]="Turn On/Off displaying the frames headers.",
                               ["HEADERFRAMESBARCOL"]="Set the bar col"..HEALBOT_enWORD_COLOUR_SUFFIX.." for the frames header.",
                               ["HEADERFRAMESTEXTCOL"]="Set the text col"..HEALBOT_enWORD_COLOUR_SUFFIX.." shown on the frames header.",
                               ["HEADERFRAMESTEXTURE"]="Set the texture for the frames header.",
                               ["HEADERFRAMESHEIGHT"]="Set the height for the frames header.",
                               ["HEADERFRAMESWIDTH"]="Set the width for the frames header.\nThis is based on the frames width.",
                               ["HEADERFRAMESFONTNAME"]="Set the font for the text\ndisplayed on the frames header.",
                               ["HEADERFRAMESFONTHEIGHT"]="Set the font size for the text\ndisplayed on the frames header.",
                               ["HEADERFRAMESFONTOUTLINE"]="Set the font outline for the text\ndisplayed on the frames header.",
                               ["HEADERFRAMESFONTOFFSET"]="Vertically offset the header text.",
                        -- Skins Frames Bars General tab
                               ["BARSGENERAL"]="Show the Skins Frames Bars General tab.\nNote: Some options are dependant on the frame selected.\n- Low mana indicator settings are not available when the Enemy frame is selected.",
                               ["HEALBARSTEXTURE"]="Set the texture for the heal bars.",
                               ["HEALBARSNUMCOLS"]="Controls how many columns will be displayed.",
                               ["HEALBARSGRPSPERCOLS"]="Sets using the number of groups for each column.",
                               ["HEALBARSHEIGHT"]="Set the height for the heal bars.",
                               ["HEALBARSWIDTH"]="Set the width for the heal bars.",
                               ["HEALBARSBRSPACE"]="Set the space between each row.",
                               ["HEALBARSBCSPACE"]="Set the space between each column.",
                               ["HEALBARSPOWERCOUNT"]="Show power indicator at\nthe bottom of the heal bar.",
                               ["HEALBARSLOWMANA"]="Set if and when indicators are\ndisplayed to show a player is low on mana.",
                               ["HEALBARSLOWMANAIC"]="Turn On/Off displaying the low\nmana indicator while in combat.",
                        -- Skins Frames Bars Colours tab
                               ["BARSCOLOUR"]="Show the Skins Frames Bars col"..HEALBOT_enWORD_COLOUR_SUFFIX.." tab.",
                               ["HEALBARSCOLHEALTHTYPE"]="Set the col"..HEALBOT_enWORD_COLOUR_SUFFIX.." of the heal bar.\nWhen custom is used click on the custom bar to set the col"..HEALBOT_enWORD_COLOUR_SUFFIX..".",
                               ["HEALBARSCOLHEALTH"]="Set the custom bar col"..HEALBOT_enWORD_COLOUR_SUFFIX.." for the heal bars.",
                               ["HEALBARSCOLALPHA"]="Set the transparency of the\nheal bar when in an enabled state.",
                               ["HEALBARSBACKCOLTYPE"]="Set the col"..HEALBOT_enWORD_COLOUR_SUFFIX.." of the background bar.\nWhen custom is used click on the custom bar to set the col"..HEALBOT_enWORD_COLOUR_SUFFIX..".",
                               ["HEALBARSBACKCOL"]="Set the custom bar col"..HEALBOT_enWORD_COLOUR_SUFFIX.." for the background bars.",
                               ["HEALBARSBACKOUTLINE"]="Set the background bar to be slightly larger than the heal bar.",
                               ["HEALBARSBACKALPHA"]="Set the transparency of the background bar.",
                               ["HEALBARSICCOLTYPE"]="Set the col"..HEALBOT_enWORD_COLOUR_SUFFIX.." of the incoming heals.\nWhen custom is used click on the custom bar to set the col"..HEALBOT_enWORD_COLOUR_SUFFIX..".",
                               ["HEALBARSICCOL"]="Set the custom col"..HEALBOT_enWORD_COLOUR_SUFFIX.." for incoming heals.",
                               ["HEALBARSICALPHA"]="Set the transparency of incoming heals.",
                               ["HEALBARSAECOLTYPE"]="Set the col"..HEALBOT_enWORD_COLOUR_SUFFIX.." of the "..HEALBOT_classicABSORBHOT.." effects.\nWhen custom is used click on the custom bar to set the col"..HEALBOT_enWORD_COLOUR_SUFFIX..".",
                               ["HEALBARSAECOL"]="Set the custom col"..HEALBOT_enWORD_COLOUR_SUFFIX.." for "..HEALBOT_classicABSORBHOT.." effects.",
                               ["HEALBARSAECOLALPHA"]="Set the transparency of "..HEALBOT_classicABSORBHOT.." effects.",
                               ["HEALBARSALPHAOOR"]="Set the transparency of the heal bars when the bar\nis in an enabled state and the player is out of range.",
                               ["HEALBARSALPHADIS"]="Set the transparency of the heal bar\nwhen the bar is in an disabled state.",
                        -- Skins Frames Bars Sort tab
                               ["BARSSORT"]="Show the Skins Frames Bars Sort tab.\nNote: Some options are dependant on the frame selected.\n- Sub sort - self first is only available when one of the User frames is selected.\n- Own pet: with self and Pets: Groups of five are only available when the Pets frame is selected.\n- This tab is not available when the Target frame or Focus frame is selected.",
                               ["HEALBARSSORTSELF"]="Sub sort self to the top of the list.\nNote: also applies to Main sort when sorting by Name or Max health.",
                               ["HEALBARSSORTOOR"]="This option is good for raids that split players, by sorting the out of range last.",
                               ["HEALBARSSORTMAIN"]="Organise how bars are sorted in the Heal Groups.",
                               ["HEALBARSSORTSUB"]="Organise how bars are sub sorted in the Main Sort.",
                               ["HEALBARSSELFPET"]="Place your own pet in the Self heal group.\nEnsure Self is turned on and high up in the Heal Groups list.",
                               ["HEALBARSPETGROUP"]="Treat pets as being in groups of five.",
                        -- Skins Frames Bars Visibility tab
                               ["BARSVISIBILITY"]="Show the Skins Frames Bars Visibility tab.\nNote: Some options are dependant on the frame selected.\n- Target settings are only available when the Target frame is selected.\n- Focus settings are only available when the Focus frame is selected.\n- Enemy settings are only displayed when the Enemy frame is selected.",
                               ["HEALBARSVISALERTIC"]="While in combat and when health is at or\nbelow this setting, the bar will become enabled.",
                               ["HEALBARSVISALERTOC"]="While out of combat and when health is at or\nbelow this setting, the bar will become enabled.",
                               ["HEALBARSVISHIDE100"]="Hide bars for players who are over 100 yards\ngenerally when not in visible in plain sight.",
                               ["HEALBARSVISTARGETIC"]="Always Show/No Change/Always Hide\nthe target frame when entering combat.\nNote: select the target frame to enable these settings.",
                               ["HEALBARSVISFOCUSIC"]="Always Show/No Change/Always Hide\nthe focus frame when entering combat.\nNote: select the focus frame to enable these settings.",
                               ["HEALBARSVISTARGETFRIEND"]="Do not show hostile targets when out of combat.",
                               ["HEALBARSVISEXCLUDERAID"]="Do not show yourself or members of your group/raid when out of combat.",
                               ["HEALBARSVISFOCUSFRIEND"]="Do not show hostile focus when out of combat.",
                               ["HEALBARSVISFILTER"]="Various classes and types can be filtered out using the dropdown.",
                               ["HEALBARSVISFILTERGROUPS"]="Groups can be filtered out using these check boxes.",
                               ["HEALBARSVISENEMYINCSELF"]="Include an enemy bar for your targets.",
                               ["HEALBARSVISENEMYINCTANKS"]="Include enemy bars for all tanks targets.",
                               ["HEALBARSVISENEMYINCARENA"]="Include enemy bars for player opponents in an arena.",
                               ["HEALBARSVISENEMYINCARENAPETS"]="Include enemy bars for pet opponents in an arena.",
                               ["HEALBARSVISENEMYINCMYTARGETS"]="Include enemy bars for all My Private List targets.",
                               ["HEALBARSVISENEMYNUMBOSSES"]="Maximum number of bars to show for bosses.",
                               ["HEALBARSVISENEMYHIDEOC"]="Hide the bars when out of combat as they will often be empty and reserved.",
                               ["HEALBARSVISENEMYSHOWTARGET"]="Show a bar for the enemy target.\n--\nFor exampe:\nA boss might be boss2target (Retail Only)\nA tank might be raid2targettarget.",
                               ["HEALBARSVISENEMYTARGETSIZE"]="The percentage of the enemy bar width\nto be used by the enemy target bar.\n--\nTip: Set a large width for Enemy bars.",
                               ["HEALBARSVISENEMYDOUBLEWIDTH"]="Double the total width for the Enemy and Enemy Target bars.\n--\nNote: This option only applies when "..HEALBOT_ENEMY_SHOW_TARGET.." is ON.",
                               ["HEALBARSVISENEMYSHOWSELF"]="On entering combat only display bars when an enemy exists.\nAllows filtering of bars that will not likely turn up during combat.\n--\nPlayer target bars - Only display your target as an enemy if the target is hostile at the start of combat.",
                               ["HEALBARSVISENEMYSHOWARENA"]="On entering combat only display bars when an enemy exists.\nAllows filtering of bars that will not likely turn up during combat.\n--\nArena opponent bars - Only display bars for existing opponents at the start of combat.",
                               ["HEALBARSVISENEMYSHOWBOSSES"]="On entering combat only display bars when an enemy exists.\nAllows filtering of bars that will not likely turn up during combat.\n--\nBoss bars - Only display bars for existing bosses at the start of combat.",
                        -- Skins Frames Bars Aggro tab
                               ["BARSAGGRO"]="Show the Skins Frames Aggro tab.\nNote: This tab is not available when the Enemy frame is selected.",
                               ["HEALBARSAGGROSHOW"]="Turn On/Off monitoring aggro.",
                               ["HEALBARSAGGROSHOWTEXT"]="Display » text « when a player has aggro.",
                               ["HEALBARSAGGROSHOWIND"]="Display small round icons on the bar when a player has aggro.",
                               ["HEALBARSAGGROPCTTXT"]="Track percentage - Display the amount of aggro a player has.\nShow text - Display text using the format selected in the dropdown.",
                               ["HEALBARSAGGROINDALERT"]="When using the indicator.\nDisplay when the treat reaches the level selected in the dropdown.",
                               ["HEALBARSAGGROBARALERT"]="When using the aggro bars.\nDisplay when the treat reaches the level selected in the dropdown.",
                        -- Skins Frames Bars Aux tab
                               ["BARSAUX"]="Show the Skins Frames Aux tab.",
                               ["BARSAUXASSIGN"]="Assign a bar type to the auxiliary bar.\n--\nNote: Only Aux 1 shows Power Points when set to Power.\nNote: Only Aux 2 shows enemy casting when set to Power.",
                               ["BARSAUXOVERLAP"]="Extend the size of the vertical or horizontal\nauxiliary bars when auxiliary bars exist on both\nthe left or right and above or below the health bar.",
                               ["BARSAUXCONFIG"]="Select the auxiliary bar to configure.",
                               ["BARSAUXCOLOUR"]="Set the col"..HEALBOT_enWORD_COLOUR_SUFFIX.." of the auxiliary bar.\nWhen custom is used click on the custom bar to set the col"..HEALBOT_enWORD_COLOUR_SUFFIX..".",
                               ["BARSAUXCOLOUROPACITYTYPE"]="Set the bars to a fixed opacity or\nflash using a variable opacity.",
                               ["BARSAUXCUSTOMCOLOUR"]="Set the custom auxiliary bar col"..HEALBOT_enWORD_COLOUR_SUFFIX..".",
                               ["BARSAUXANCHOR"]="Auxiliary bar anchor relative to the health bar.",
                               ["BARSAUXSIZE"]="The size of the auxiliary bar.\nThis is based on the health bar.",
                               ["BARSAUXDEPTH"]="The depth of the auxiliary bar.\nWhen in vertical orientation this is the width.\nWhen in horizontal orientation this is the height.",
                               ["BARSAUXOFFSET"]="The auxiliary bar offset, relative to the next\nauxiliary bar or health bar depending on configuration.",
                        -- Skins Frames Text Name tab
                               ["TEXTNAME"]="Show the Skins Frames Text Name tab.",
                               ["HEALBARSCOLTEXTNAME"]="Set the col"..HEALBOT_enWORD_COLOUR_SUFFIX.." of the name text.\nWhen custom is used click on the custom bar to set the col"..HEALBOT_enWORD_COLOUR_SUFFIX..".",
                               ["HEALBARSCOLCUSTOMTEXTNAME"]="Set the custom name text col"..HEALBOT_enWORD_COLOUR_SUFFIX,
                               ["HEALBARSNAMETEXTCOLALPHA"]="Set the transparency of the\nname text when in an enabled state.",
                               ["HEALBARSNAMETEXTDISCOLALPHA"]="Set the transparency of the\nname text when in a disabled state.",
                               ["HEALBARSNAMETEXTDEBUFF"]="Always use the Custom col"..HEALBOT_enWORD_COLOUR_SUFFIX.."\nwhen the player has a debuff.",
                               ["HEALBARSTXTSHOWNAME"]="Show the players name on the bar.",
                               ["HEALBARSTXTUTF8"]="Improve compatibility with international characters.\nNote: when on an English only server it is recommended to turn this off.",
                               ["HEALBARSTXTSHOWCLASS"]="Include the class on the bar.",
                               ["HEALBARSTXTSHOWROLE"]="Show the players role in the group/raid when available.\nNote: This replaces the class.",
                               ["HEALBARSTXTSHOWCLASSICON"]="Show the class/role as an icon.",
                               ["HEALBARSTXTSHOWCLASSTEXT"]="Show the class/role as text.",
                               ["HEALBARSTXTTAGDC"]="Display a tag before the characters name when the player is "..HEALBOT_DISCONNECTED_LABEL..".",
                               ["HEALBARSTXTTAGRIP"]="Display a tag before the characters name when the player is "..HEALBOT_DEAD_LABEL..".",
                               ["HEALBARSTXTTAGOOR"]="Display a tag before the characters name when the player is "..HEALBOT_OUTOFRANGE_LABEL..".",
                               ["HEALBARSTXTTAGR"]="Display a tag before the characters name when the bar is "..HEALBOT_RESERVED_LABEL..".",
                               ["HEALBARSTXTFONT"]="Set the font for the text\ndisplayed on the heal bar.",
                               ["HEALBARSTXTFONTHEIGHT"]="Set the font size for the text\ndisplayed on the heal bars.",
                               ["HEALBARSTXTFONTOFFSET"]="Vertically offset the bar text.",
                               ["HEALBARSTXTFONTALIGN"]="Horizontally set the bar text.",
                               ["HEALBARSTXTFONTHOFFSET"]="Horizontally offset the bar text.",
                               ["HEALBARSTXTFONTOUTLINE"]="Set the font outline for the text\ndisplayed on the heal bars.",
                               ["HEALBARSTXTMAXCHARS"]="Set the maximum number of characters shown on the heal bar.\nAuto will generally calculate the maximum number of characters\nto fit within the bar when standard fonts are used.",
                        -- Skins Frames Text Health tab
                               ["TEXTHEALTH"]="Show the Skins Frames Health Name tab.",
                               ["HEALBARSCOLTEXTHEALTH"]="Set the col"..HEALBOT_enWORD_COLOUR_SUFFIX.." of the health text.\nWhen custom is used click on the custom bar to set the col"..HEALBOT_enWORD_COLOUR_SUFFIX..".",
                               ["HEALBARSCOLCUSTOMTEXTHEALTH"]="Set the custom health text col"..HEALBOT_enWORD_COLOUR_SUFFIX,
                               ["HEALBARSHEALTHTEXTCOLALPHA"]="Set the transparency of the\nhealth text when in an enabled state.",
                               ["HEALBARSHEALTHTEXTDISCOLALPHA"]="Set the transparency of the\nhealth text when in a disabled state.",
                               ["HEALBARSTXTSHOWHEALTH"]="Show the players health on the bar.",
                               ["HEALBARSTXTHEALTHICOPTION"]="NOTE: Incoming heals text is only shown on enabled bars.\n--\n- No Incoming Heals - Never show incoming heals.\n- Include incoming heals - Include incoming heals in the health text.\n- Separate incoming heals - Show incoming heals next to the health text.",
                               ["HEALBARSTXTHEALTHICAOPTION"]="NOTE: "..HEALBOT_classicABSORBHOT.."s text is only shown on enabled bars.\n--\n- No Incoming "..HEALBOT_classicABSORBHOT.."s - Never show "..HEALBOT_classicABSORBHOT.."s.\n- Include "..HEALBOT_classicABSORBHOT.."s - Include "..HEALBOT_classicABSORBHOT.."s in the health text.\n- Separate "..HEALBOT_classicABSORBHOT.."s - Show "..HEALBOT_classicABSORBHOT.."s next to the health text.",
                               ["HEALBARSTXTHEALTHSOHEALS"]="NOTE: Overhealing text is only shown on\nenabled bars and always separate from other heals.\n--\n- No Overheals - Never show Overheals.\n- Show my overheals - Show your overhealing next to the health text.\n- Show all overheals - Show all overhealing next to the health text.",
                               ["HEALBARSTXTHLTHANCHOR"]="Set how the health text anchors to the name text.",
                               ["HEALBARSTXTIGNOREINFULL"]="Ignore all incoming heals and "..HEALBOT_classicABSORBHOT.."s\nwhen the player is on full health.\n--\nNote:When this option is off, incoming heals and "..HEALBOT_classicABSORBHOT.."s\nare always shown when the bar is enabled.",
                               ["HEALBARSTXTHEALTHTYPE"]="Various options on how the health is displayed.",
                               ["HEALBARSTXTHEALTHFORMAT"]="Various options on the number format for health.",
						-- Skins Frames Icons  tab
							   ["ICONSDEBUFFS"]="Show the Skins Frames Icons Debuffs tab",
							   ["ICONSBUFFS"]="Show the Skins Frames Icons Buffs tab",
							   ["ICONSEXTRA"]="Show the Skins Frames Icons Extras tab",
							   ["ICONPOSITION"]="Set the position of icons",
							   ["ICONANCHOR"]="Set the location of icons based on the position",
                        -- Skins Frames Icons Aura General tab
                               ["ICONSDEBUFFGENERAL"]="Show the Skins Frames Icons Debuffs General tab.",
							   ["ICONSBUFFGENERAL"]="Show the Skins Frames Icons Buffs General tab.",
                               ["ICONNUMHOT"]="Select the maximum number\nof buff and HoT icons to show.",
                               ["ICONNUMDEBUFF"]="Select the maximum number of debuff\nand Role/Class, Target Marker icons to show.",
                               ["ICONDOUBLE"]="Show 2 rows of icons taking less horizontal space.\nNote: Icon scale is halved when using this setting.",
                               ["ICONSCALE"]="The icon scale relative to the bar.\nNote: The scale is halved when using Double row.",
                               ["ICONALWAYSEN"]="Always use enabled bar opacity setting even\nwhen the bar is using a different setting.",
                               ["ICONFADE"]="Fade the icon as it begins to expire.",
                               ["ICONFADESTART"]="The number of seconds before expiry when the icon fades.\n--\nNOTE: The fade is gradual and generally not noticeable for the first few seconds.",
                        -- Skins Frames Icons Aura Text tab
                               ["ICONSDEBUFFTEXT"]="Show the Skins Frames Icons Debuffs Text tab.",
						       ["ICONSBUFFTEXT"]="Show the Skins Frames Icons Buffs Text tab.",
                               ["ICONTXTSHOWCOUNT"]="Set the type of text and conditions met to show text on the icon.\nCount - Show the number of stacks, for all casters or own casts if Self casts only is on.",
                               ["ICONTXTSHOWDUR"]="Set the type of text and conditions met to show text on the icon.\nDuration - Show the duration remaining, for all casters or own casts if Self casts only is on.",
                               ["ICONTXTDURTIME"]="Only show the duration when the remaining\nduration is under the slider amount.",
                               ["ICONTXTDURWARNTIME"]="Change the text colour to red for buffs and green for debuffs\nwhen the remaining duration is under the slider amount.",
                               ["ICONTXTFONT"]="Set the font for the text\ndisplayed on the icons.",
                               ["ICONTXTFONTSIZE"]="Set the font size for the\ntext displayed on the icons.",
                               ["ICONTXTFONTOUTLINE"]="Set the font outline for the\ntext displayed on the icons.",
                        -- Skins Frames Icons Extra tabs
						       ["ICONSCLASSROLE"]="Show the Skins Frames Icons Extras Class / Role tab.",
						       ["ICONSRAIDTARGET"]="Show the Skins Frames Icons Extras Raid Target tab.",
                               ["ICONSHOWCLASS"]="Shows the Class or Role when set.",
                               ["ICONSHOWRC"]="Shows the ready check status.",
                               ["ICONSHOWRT"]="Show the raid target when assigned to a player.\nThe target types can be individually filtered.",
                               ["ICONSHOWDIR"]="Show a direction arrow pointing at players out of range.\nNote: This only works outside.",
                               ["ICONSHOWDIRMO"]="Only show the direction arrow\nwhen the mouse is over the bar.",
						       ["ICONSREADYCHECK"]="Show the Skins Frames Icons Extras Ready Check tab.",
						       ["ICONSOORARROW"]="Show the Skins Frames Icons Extras Out of Range Arrow tab.",
						       ["ICONOFFSET"]="Offset the extra icon relative to the anchor.",
                        -- Debuffs General tab
                               ["MONITORDEBUFFS"]="Turn on/off debuff monitoring.",
                               ["MONITORDEBUFFSIC"]="Turn on/off monitoring for debuffs in combat.",
                               ["MONITORDEBUFFSGROUPED"]="Do not monitor debuffs when solo.",
                               ["DEBUFFSSPELLTOCURE"]="The spell to use.\nDebuffs displayed will only be those that the spell can remove.",
                               ["DEBUFFSSPELLCHECKMEMBERS"]="The members to monitor.",
                               ["DEBUFFSIGNOREDEBUFFS"]="Debuffs with little or no effect can be ignored.\n- Short duration - Ignore debuffs that last for less time than the Duration slider\n- When cure spell CoolDown > 2secs - Ignore debuffs when its not possible to cast while the spell is on cooldown\n- When caster is known as friend - When the caster of the debuff is friendly",
                               ["DEBUFFSTYPEPRIORITY"]="Priority by debuff types.\nHighest priority is 1 and lowest is 20, highest priority is always displayed first.",
                               ["DEBUFFSTYPECOLOUR"]="Bars are changed to defined col"..HEALBOT_enWORD_COLOUR_SUFFIX.."s by debuff types. Click to change.\nWhen the player has a debuff and settings on the Debuff Warning tab apply.",
                        -- Debuffs Custom tab
                               ["DEBUFFSCUSTOMCAT"]="Custom defaults and A-Z debuff categories\ncan be selected using the category dropdown.",
                               ["DEBUFFSCUSTOMIDMETHOD"]="Check debuffs using Spell ID, Spell Name or Both.",
                               ["DEBUFFSCUSTOMDEBUFF"]="Lists custom default settings or individual\ndebuffs depending on the Category selected.",
                               ["DEBUFFSCUSTOMCASTBY"]="Sets a filter on debuffs displayed\nby checking the caster of the debuff.",
                               ["DEBUFFSCUSTOMDELETE"]="Delete the selected custom debuff.",
                               ["DEBUFFSCUSTOMNEWNAME"]="Add a new debuff to the current category.\nNote: The Spell Name or Spell ID can be used.\nUsing Spell ID is recommended.",
                               ["DEBUFFSCUSTOMNEWSAVE"]="Save the new custom debuff.",
                               ["DEBUFFSCUSTOMENDIS"]="Disable the selected custom debuff in the current zone.",
                               ["DEBUFFSCUSTOMPRIORITY"]="Priority of the selected custom debuff.\nHighest priority is 1 and lowest is 20, highest priority is always displayed first.",
                               ["DEBUFFSCUSTOMCOLOUR"]="Click on the custom bar to set the col"..HEALBOT_enWORD_COLOUR_SUFFIX..".",
                               ["DEBUFFSCUSTOMCOLOURSHOW"]="Turn on/off changing the bar col"..HEALBOT_enWORD_COLOUR_SUFFIX.." for the selected custom debuff.",
                               ["DEBUFFSCUSTOMRESET"]="Reset settings to defaults for the selected custom debuff.",
                               ["DEBUFFSCUSTOMPAGE"]="Page though the custom debuffs.",
                               ["DEBUFFSCUSTOMALLDISEASE"]="Always show disease type debuffs.",
                               ["DEBUFFSCUSTOMALLMAGIC"]="Always show magic type debuffs.",
                               ["DEBUFFSCUSTOMALLPOISON"]="Always show poison type debuffs.",
                               ["DEBUFFSCUSTOMALLCURSE"]="Always show curse type debuffs.",
                               ["DEBUFFSCUSTOMALLBOSS"]="Always show debuffs cast by bosses.",
                               ["DEBUFFSCUSTOMALLTIMED"]="Always show debuffs with a duration less than "..HealBot_Config_Cures.ShowTimeMaxDuration.." seconds.\n--\nNOTE: Excludes debuffs cast by friendly players.\nNOTE: Use '/hb atd n' to set the duration where n is the seconds.",
                        -- Debuffs Warning tab
                               ["DEBUFFSWARNINGBAR"]="Change the health bar col"..HEALBOT_enWORD_COLOUR_SUFFIX.." to the settings defined.\nThis applies to all General and Custom debuffs.",
                               ["DEBUFFSWARNINGBARRANGE"]="Set the range when the health bar col"..HEALBOT_enWORD_COLOUR_SUFFIX.." is changed.",
                               ["DEBUFFSWARNINGSHOW"]="Display a text warning on screen.\nThis applies to all General and Custom debuffs.",
                               ["DEBUFFSWARNINGSHOWRANGE"]="Set the range when the on screen text is displayed.",
                               ["DEBUFFSWARNINGSOUND"]="Play a sound.\nThis applies to all General and Custom debuffs.",
                               ["DEBUFFSWARNINGSOUNDRANGE"]="Set the range when the sound is played.",
                               ["DEBUFFSWARNINGSOUNDSELECT"]="Select the sound to play.",
                               ["DEBUFFSWARNINGSOUNDPREVIEW"]="Test playing the sound.",
                               ["DEBUFFSWARNINGSPAMFILTER"]="Minimum seconds for warnings of the same debuff.\n--\nNOTE: This applies to all players with the same debuff.",
                        -- Buffs General tab
                               ["MONITORBUFFS"]="Turn on/off buff monitoring.",
                               ["MONITORBUFFSIC"]="Turn on/off monitoring for buffs in combat.",
                               ["MONITORBUFFSGROUPED"]="Do not monitor buffs when solo.",
                               ["MONITORBUFFSPALABLESSING"]="Ignore if player has any blessing cast by you.",
                               ["BUFFSSPELL"]="Select the spell to monitor and cast.",
                               ["BUFFSMEMBERS"]="The members to monitor.",
                               ["BUFFSBARS"]="Bars are changed to defined col"..HEALBOT_enWORD_COLOUR_SUFFIX..". Click to change.\nWhen the player is missing a buff and settings on the Buff Warning tab apply.",
                               ["BUFFSTIMER"]="Alert when a buff is required n mins/secs before it expires.\n- Show buffs - These are buffs with a duration of a few minutes or less.\n- Long buffs - These are buffs with a duration usually in the 10's of minutes or more.",
                        -- Buffs Custom tab
                               ["BUFFSCUSTOMCAT"]="Custom class categories can be selected using the category dropdown.",
                               ["BUFFSCUSTOMBUFF"]="Lists custom buffs depending on the Category selected.",
                               ["BUFFSCUSTOMIDMETHOD"]="Check buffs using Spell ID, Spell Name or Both.",
                               ["BUFFSCUSTOMCASTBY"]="Sets a filter on buffs displayed\nby checking the caster of the buff.",
                               ["BUFFSCUSTOMDELETE"]="Delete the selected custom buff.",
                               ["BUFFSCUSTOMNEWNAME"]="Add a new buff to the current category.\nNote: The Spell Name or Spell ID can be used.\nUsing Spell ID is recommended.",
                               ["BUFFSCUSTOMNEWSAVE"]="Save the new custom buff.",
                               ["BUFFSCUSTOMENDIS"]="Disable the selected custom buff in the current zone.",
                               ["BUFFSCUSTOMPRIORITY"]="Priority of the selected custom buff.\nHighest priority is 1 and lowest is 20, highest priority is always displayed first.",
                               ["BUFFSCUSTOMCOLOUR"]="Click on the custom bar to set the col"..HEALBOT_enWORD_COLOUR_SUFFIX..".",
                               ["BUFFSCUSTOMCOLOURSHOW"]="Turn on/off changing the bar col"..HEALBOT_enWORD_COLOUR_SUFFIX.." for the selected custom buff.",
                               ["BUFFSCUSTOMRESET"]="Reset settings to defaults for the selected custom buff.",
                               ["BUFFSCUSTOMPAGE"]="Page though the custom buffs.",
                        -- Buffs Warning tab
                               ["BUFFSWARNINGBAR"]="Change the health bar col"..HEALBOT_enWORD_COLOUR_SUFFIX.." to the settings defined.\nThis applies to all General and Custom buffs.",
                               ["BUFFSWARNINGBARRANGE"]="Set the range when the health bar col"..HEALBOT_enWORD_COLOUR_SUFFIX.." is changed.",
                               ["BUFFSWARNINGSHOW"]="Display a text warning on screen.\nThis applies to all General and Custom buffs.",
                               ["BUFFSWARNINGSHOWRANGE"]="Set the range when the on screen text is displayed.",
                               ["BUFFSWARNINGSOUND"]="Play a sound.\nThis applies to all General and Custom buffs.",
                               ["BUFFSWARNINGSOUNDRANGE"]="Set the range when the sound is played.",
                               ["BUFFSWARNINGSOUNDSELECT"]="Select the sound to play.",
                               ["BUFFSWARNINGSOUNDPREVIEW"]="Test playing the sound.",
                        -- Tips tab
                               ["TOOLTIPSHOW"]="Show tooltip information on the\ncurrent bar the mouse is over.",
                               ["TOOLTIPHIDEIC"]="Hide the tooltip when in combat.",
                               ["TOOLTIPTARGETINFO"]="Show the name, class and spec if relevant,\nlocation, health and mana/power.",
                               ["TOOLTIPMYBUFFS"]="Show buffs and duration cast by you.",
                               ["TOOLTIPSPELLDETAIL"]="Show the cast time of the spell.",
                               ["TOOLTIPSPELLCD"]="Show the cooldown remaining on the spell.",
                               ["TOOLTIPIGNORESPELLGCD"]="Ignore the global cooldown on the spell.",
                               ["TOOLTIPWHEELCMD"]="Show the commands defined on the Mouse Wheel tab.",
                               ["TOOLTIPHOTREC"]="Show best HoT depending on current circumstances.",
                               ["TOOLTIPGAMETIP"]="Use the game tooltip, this includes tooltip addons.",
                               ["TOOLTIPMONBUFFS"]="On all monitored Buffs / HoT's\nshow who cast the spell and duration left.",
                               ["TOOLTIPFONTSIZE"]="Set the size using Blizzards standard font sizes.",
                               ["TOOLTIPPOSITIONLINK"]="Links to the Skins Frame General tab,\nallowing for different positions per frame.",
                               ["TOOLTIPALPHA"]="Set the transparency of the tooltip.",
                        -- Mouse Wheel tab
                               ["BUFFSMOUSEWHEELUSE"]="Turn On/Off usage of the mouse wheel.\nNote: When this is on mouse over macros will not work on HealBot bars",
                               ["BUFFSMOUSEWHEELCMD"]="Set a command to run with an optional key press\nand mouse wheel up or down combination.",
                               ["BUFFSMOUSEWHEELEMOTE"]="Select the emote to be used on mouse wheel scroll.",
                        -- Test tab
                               ["TESTUSE"]="The button shows the current state of test bars, click on it to change the state.",
                               ["TESTPROFILE"]="Profile limits the total number of bars for Groups or Raids.",
                               ["TESTNUMTOTAL"]="Fine tune the total number of bars for selected profile.",
                               ["TESTNUMTANKS"]="Set the number of bars to represent Tanks.",
                               ["TESTNUMHEALS"]="Set the number of bars to represent Healers.",
                               ["TESTNUMMYTARGETS"]="Set the number of bars to represent your Private Targets.",
                               ["TESTNUMPETS"]="Set the number of bars to represent Pets.",
                               ["TESTNUMENEMY"]="Set the number of bars to represent the Enemy.",
                        -- Import/Export tab
                               ["INOUTSKINS"]="Show the Import/Export Skins tab.",
                               ["INOUTCUSTOMDEBUFFS"]="Show the Import/Export Custom Debuffs tab.",
                               ["INOUTCUSTOMBUFFS"]="Show the Import/Export Custom Buffs tab.",
                               ["INOUTSPELLS"]="Show the Import/Export Spells tab.",
                               ["INOUTPRESETCOLS"]="Show the Import/Export Preset Col"..HEALBOT_enWORD_COLOUR_SUFFIX.."s tab.",
                        -- Import/Export Skins tab
                               ["INOUTSELECTSKIN"]="Select the skin to be exported.",
                               ["INEXTRASKIN"]="Select an extra skin to import.\n--\nNOTE: After importing extra skins, delete any that are not used.\nThis will reduce the addons main memory usage.\n--\nNOTE: Images can be viewed at "..HEALBOT_ABOUT_URL,
                               ["INOUTEXPORTSKIN"]="Export populates the large text box with data for the selected skin.\nThis can then be copied and saved outside the game.\n--\nTIP: To reduce the number of characters, first do the following:\nFor all tabs possible, in Skins>Frames, select the top frame and use Apply current tab settings to all Frames.",
                               ["INOUTIMPORTSKIN"]="Import reads the text from the large text box and sets the skin.\nNote: This will overwrite any existing skin with the same name.",
                        -- Import/Export Custom Debuffs tab
                               ["INOUTEXPORTCDEBUFF"]="Export populates the large text box with data of all current custom debuffs.\nThis can then be copied and saved outside the game.",
                               ["INOUTIMPORTCDEBUFFMETHOD"]="On Import the following methods can be used.\n- Overwrite All - Delete all existing custom debuffs, then load and insert custom debuffs.\n- Merge All - Insert missing custom debuffs and update existing custom debuffs.\n- Merge New - Only insert missing custom debuffs, no updates to existing custom debuffs.",
                               ["INOUTIMPORTCDEBUFF"]="Import loads in the data from the large text box\nusing the import method selected above.",
                        -- Import/Export Custom Buffs tab
                               ["INOUTEXPORTCBUFF"]="Export populates the large text box with data of all current custom buffs.\nThis can then be copied and saved outside the game.",
                               ["INOUTIMPORTCBUFFMETHOD"]="On Import the following methods can be used.\n- Overwrite All - Delete all existing custom buffs, then load and insert custom buffs.\n- Merge All - Insert missing custom buffs and update existing custom buffs.\n- Merge New - Only insert missing custom buffs, no updates to existing custom buffs.",
                               ["INOUTIMPORTCBUFF"]="Import loads in the data from the large text box\nusing the import method selected above.",
                        -- Import/Export Spells tab
                               ["INOUTEXPORTSPELLS"]="Export populates the large text box with data of all current spells.\nThis can then be copied and saved outside the game.",
                               ["INOUTIMPORTSPELLSMETHOD"]="On Import the following methods can be used.\n- Overwrite All - Delete all existing spells, then load and insert spells.\n- Merge All - Insert missing spells and update existing spells.\n- Merge New - Only insert missing spells, no updates to existing spells.",
                               ["INOUTIMPORTSPELLS"]="Import loads in the data from the large text box\nusing the import method selected above.",
                        -- Import/Export Preset Colours tab
                               ["INOUTEXPORTPRESETCOLS"]="Export populates the large text box with data of all preset col"..HEALBOT_enWORD_COLOUR_SUFFIX.."s.\nThis can then be copied and saved outside the game.",
                               ["INOUTIMPORTPRESETCOLS"]="Import loads in the data from the large text box.",
                              }
end
