HealBot_Default_Textures={
    [1]= {name="HealBot 01", file=[[Interface\Addons\HealBot\Images\bar1.tga]]},
    [2]= {name="Waves", file=[[Interface\Addons\HealBot\Images\bar2.tga]]},
    [3]= {name="HealBot 03", file=[[Interface\Addons\HealBot\Images\bar3.tga]]},
    [4]= {name="HealBot 04", file=[[Interface\Addons\HealBot\Images\bar4.tga]]},
    [5]= {name="HealBot 05", file=[[Interface\Addons\HealBot\Images\bar5.tga]]},
    [6]= {name="BantoBar", file=[[Interface\Addons\HealBot\Images\bar6.tga]]},
    [7]= {name="Otravi", file=[[Interface\Addons\HealBot\Images\bar7.tga]]},
    [8]= {name="Smooth", file=[[Interface\Addons\HealBot\Images\bar8.tga]]},
    [9]= {name="Charcoal", file=[[Interface\Addons\HealBot\Images\bar9.tga]]},
    [10]= {name="HealBot 10", file=[[Interface\Addons\HealBot\Images\bar10.tga]]},
    [11]= {name="Diagonal", file=[[Interface\Addons\HealBot\Images\bar11.tga]]},
    [12]= {name="Skewed", file=[[Interface\Addons\HealBot\Images\bar12.tga]]},
    [13]= {name="Marble", file=[[Interface\Addons\HealBot\Images\bar13.tga]]},
    [14]= {name="HealBot 14", file=[[Interface\Addons\HealBot\Images\bar14.tga]]},
    [15]= {name="Healbot", file=[[Interface\Addons\HealBot\Images\Bar15.tga]]},
    [16]= {name="Tukui", file=[[Interface\Addons\HealBot\Images\normTex.tga]]},----Tukui-----
    [17]= {name="Tukui2", file=[[Interface\Addons\HealBot\Images\DsmV1.tga]]},-----Tukui-----
    [18]= {name="Tukui4", file=[[Interface\Addons\HealBot\Images\tukuibar.tga]]},----TUKUI----
    [19]= {name="Flat", file=[[Interface\Addons\HealBot\Images\Flat.tga]]},
    [20]= {name="Smooth v2", file=[[Interface\Addons\HealBot\Images\Smoothv2.tga]]},
};
HealBot_Default_Sounds={
    [1]= {name="Tribal Bass Drum", file=566027},
    [2]= {name="Thorns", file=569022},
    [3]= {name="Elf Bell Toll", file=566558},
};
HealBot_Default_Fonts={
    [1]= {name="Aovel Sans Black", file=[[Interface\AddOns\HealBot\Fonts\ASansBlack.ttf]]},
    [2]= {name="Ace Futurism", file=[[Interface\AddOns\HealBot\Fonts\ace_futurism.ttf]]},
    [3]= {name="Oregon LDO Black", file=[[Interface\AddOns\HealBot\Fonts\Oregon_LDO_Black.ttf]]},
    [4]= {name="Oregon LDO Bold", file=[[Interface\AddOns\HealBot\Fonts\Oregon_LDO_Bold.ttf]]},
    [5]= {name="Playball", file=[[Interface\AddOns\HealBot\Fonts\Playball.ttf]]},
    [6]= {name="Special Elite", file=[[Interface\AddOns\HealBot\Fonts\SpecialElite.ttf]]},
    [7]= {name="SpicyRice", file=[[Interface\AddOns\HealBot\Fonts\SpicyRice_Regular.ttf]]},
    [8]= {name="Star Jedi", file=[[Interface\AddOns\HealBot\Fonts\Star_Jedi_Rounded.ttf]]},
    [9]= {name="Swansea", file=[[Interface\AddOns\HealBot\Fonts\SWANSE__.ttf]]},
    [10]= {name="Swansea Bold", file=[[Interface\AddOns\HealBot\Fonts\SWANSE_B.ttf]]},
    [11]= {name="Cognosis", file=[[Interface\AddOns\HealBot\Fonts\Cognosis.ttf]]},
    [12]= {name="Myriad", file=[[Interface\AddOns\HealBot\Fonts\Myriad.ttf]]},
    [13]= {name="NotoSans Bold", file=[[Interface\AddOns\HealBot\Fonts\NotoSans-Bold.ttf]]},
    [14]= {name="Roboto Bold", file=[[Interface\AddOns\HealBot\Fonts\Roboto-Bold.ttf]]},
    [15]= {name="Roboto Medium", file=[[Interface\AddOns\HealBot\Fonts\Roboto-Medium.ttf]]},
};
--HealBot_Default_Font= "Friz Quadrata TT";
HealBot_Default_Font=HealBot_Default_Fonts[15].name
HealBot_Font_Outline={
    [1]= "",
    [2]= "OUTLINE",
    [3]= "THICKOUTLINE",
};

local Version=HealBot_Global_Version()
HealBot_ConfigDefaults = {
  LastVersionUpdate=Version,
  MyFriend="x",
  CurrentSpec=9,
  Spec="",
  CurrentLoadout=0,
  LastLoadout=0,
  Skin_ID = -1,
  MacroUse10 = false,
  DisableHealBot=false,
  DisableSolo=false,
  DisabledNow=0,
  LastAutoSkinChangeType="-",
  LastAutoSkinChangeTime=0,
  KnownLoadouts={},
  SkinDefault = {[HEALBOT_SKINS_STD]          = {[HEALBOT_WORD_SOLO]=false, 
                                                 [HEALBOT_WORD_PARTY]=false, 
                                                 [HEALBOT_OPTIONS_RAID10]=false, 
                                                 [HEALBOT_OPTIONS_RAID25]=false, 
                                                 [HEALBOT_OPTIONS_RAID40]=false,
                                                 [HEALBOT_WORD_ARENA]=false, 
                                                 [HEALBOT_WORD_BG10]=false, 
                                                 [HEALBOT_WORD_BG15]=false, 
                                                 [HEALBOT_WORD_BG40]=false, 
                                                 [HEALBOT_WORD_PETBATTLE]=false}, 
                 [HEALBOT_OPTIONS_GROUPHEALS] = {[HEALBOT_WORD_SOLO]=false, 
                                                 [HEALBOT_WORD_PARTY]=false, 
                                                 [HEALBOT_OPTIONS_RAID10]=false, 
                                                 [HEALBOT_OPTIONS_RAID25]=false, 
                                                 [HEALBOT_OPTIONS_RAID40]=false,
                                                 [HEALBOT_WORD_ARENA]=false, 
                                                 [HEALBOT_WORD_BG10]=false, 
                                                 [HEALBOT_WORD_BG15]=false, 
                                                 [HEALBOT_WORD_BG40]=false, 
                                                 [HEALBOT_WORD_PETBATTLE]=false}, 
                 [HEALBOT_OPTIONS_RAID25]     = {[HEALBOT_WORD_SOLO]=false, 
                                                 [HEALBOT_WORD_PARTY]=false, 
                                                 [HEALBOT_OPTIONS_RAID10]=false, 
                                                 [HEALBOT_OPTIONS_RAID25]=false, 
                                                 [HEALBOT_OPTIONS_RAID40]=false,
                                                 [HEALBOT_WORD_ARENA]=false, 
                                                 [HEALBOT_WORD_BG10]=false, 
                                                 [HEALBOT_WORD_BG15]=false, 
                                                 [HEALBOT_WORD_BG40]=false, 
                                                 [HEALBOT_WORD_PETBATTLE]=false}, 
                 [HEALBOT_OPTIONS_RAID40]     = {[HEALBOT_WORD_SOLO]=false, 
                                                 [HEALBOT_WORD_PARTY]=false, 
                                                 [HEALBOT_OPTIONS_RAID10]=false, 
                                                 [HEALBOT_OPTIONS_RAID25]=false, 
                                                 [HEALBOT_OPTIONS_RAID40]=false,
                                                 [HEALBOT_WORD_ARENA]=false, 
                                                 [HEALBOT_WORD_BG10]=false, 
                                                 [HEALBOT_WORD_BG15]=false, 
                                                 [HEALBOT_WORD_BG40]=false, 
                                                 [HEALBOT_WORD_PETBATTLE]=false},
                },
  SkinZoneEnabled={},
  SkinSpecEnabled={},
  EnableHealthy = true,
  Profile=1,
  BuffReset="6.0.0",
  };

HealBot_Config_SpellsDefaults = {
  EnabledKeyCombo={["New"]=true},
  EnabledSpellTarget={},
  EnabledSpellTrinket1={},
  EnabledSpellTrinket2={},
  EnabledAvoidBlueCursor={},
  EnemyKeyCombo={},
  EnemySpellTarget={},
  EnemySpellTrinket1={},
  EnemySpellTrinket2={},
  EnemyAvoidBlueCursor={},
  EmergKeyCombo={},
  EmergSpellTarget={},
  EmergSpellTrinket1={},
  EmergSpellTrinket2={},
  EmergAvoidBlueCursor={},
  ButtonCastMethod = 2,
  Binds={[1]=1,[2]=1,[3]=1,[4]=1,[5]=1,[6]=1,[7]=1,[8]=1,[9]=1,[10]=1,[11]=1,[12]=1,[13]=1,[14]=1,[15]=1,[16]=1,[17]=1,[18]=1,[19]=1,[20]=1,}
};

HealBot_Config_BuffsDefaults = {
  BuffWatch=true,
  BuffWatchInCombat=false,
  PalaBlessingsAsOne=false,
  ShortBuffTimer=10,
  LongBuffTimer=120,
  AutoBuff=1,
  AutoBuffCastBy=1,
  ListSortOrder=1,
  ListSortFilter=1,
  ListSortFilterTag="",
  AutoBuffExpireTime=31,
  BuffWatchWhenGrouped=false,
  BuffWatchWhenMounted=false,
  NoAuraWhenRested=false,
  ExtraBuffsOnlyInInstance=false,
  HealBotBuffText={},
  HealBotBuffDropDown={},
  HealBotBuffColR={},
  HealBotBuffColG={},
  HealBotBuffColB={},
  AlwaysShowSelf = false,
  AlwaysShowClass = false,
  AlwaysShowTimed = false,
  CBshownHB=true,
  ShowGroups={[1]=true, [2]=true, [3]=true, [4]=true, [5]=true, [6]=true, [7]=true, [8]=true, },
  ShowBuffWarning=false,
  SoundBuffWarning=false,
  SoundBuffPlay=HealBot_Default_Sounds[1].name,
  HealBot_CBWarnRange_Bar=3,
  HealBot_CBWarnRange_Screen=2,
  HealBot_CBWarnRange_Sound=3,
  CustomBuffCheck={[1]=false, [2]=false, [3]=false},
  CustomBuffName={[1]="", [2]="", [3]=""},
  CustomItemName={[1]="", [2]="", [3]=""},
  ManaDrinkThreshold=50,
  ManaDrinkItem="",
  WellFedItem="",
  BackupManaDrinkItem="",
  BackupWellFedItem="",
};

HealBot_Config_CuresDefaults = {
  SoundDebuffWarning = false,
  DebuffWatch = true,
  IgnoreFastDurDebuffs = true,
  IgnoreFastDurDebuffsSecs=2,
  IgnoreOnCooldownDebuffs = false,
  IgnoreFriendDebuffs = false,
  SoundDebuffPlay = HealBot_Default_Sounds[1].name,
  DebuffWatchInCombat = true,
  DebuffWatchWhenGrouped = false,
  DebuffWatchWhenMounted = false,
  ShowDebuffWarning = true,
  AlwaysShowBoss = true,
  AlwaysShowTimed = false,
  ListSortOrder=1,
  ListSortFilter=1,
  ListSortFilterTag="",
  ShowTimeMaxDuration = 31,
  CDCshownHB=true,
  ShowGroups={[1]=true, [2]=true, [3]=true, [4]=true, [5]=true, [6]=true, [7]=true, [8]=true, },
  HealBot_CDCWarnRange_Bar=3,
  HealBot_CDCWarnRange_Screen=2,
  HealBot_CDCWarnRange_Sound=3,
  HealBotDebuffText={},
  HealBotDebuffDropDown={},
  HealBotDebuffPriority={
    [HEALBOT_DISEASE_en] = 7,
    [HEALBOT_MAGIC_en] = 5,
    [HEALBOT_POISON_en] = 8,
    [HEALBOT_CURSE_en] = 6,
    [HEALBOT_CUSTOM_en] = 15,
  },
  CDCBarColour = {
    [HEALBOT_DISEASE_en] = { R = 0.55, G = 0.19, B = 0.7, },
    [HEALBOT_MAGIC_en] = { R = 0.26, G = 0.33, B = 0.83, },
    [HEALBOT_POISON_en] = { R = 0.12, G = 0.46, B = 0.24, },
    [HEALBOT_CURSE_en] = { R = 0.83, G = 0.43, B = 0.09, },
  },
  HealBot_Custom_Debuffs_All = {
    [HEALBOT_DISEASE_en] = false,
    [HEALBOT_MAGIC_en]   = false,
    [HEALBOT_POISON_en]  = false,
    [HEALBOT_CURSE_en]   = false,
  },
};
HealBot_Class_En = { 
                [HEALBOT_CLASSES_ALL]="ALL",
                [HEALBOT_DRUID]="DRUI",
                [HEALBOT_HUNTER]="HUNT",
                [HEALBOT_MAGE]="MAGE",
                [HEALBOT_PALADIN]="PALA",
                [HEALBOT_PRIEST]="PRIE",
                [HEALBOT_ROGUE]="ROGU",
                [HEALBOT_SHAMAN]="SHAM",
                [HEALBOT_WARLOCK]="WARL",
                [HEALBOT_WARRIOR]="WARR",
                [HEALBOT_EVOKER]="EVOK",
                [HEALBOT_DEATHKNIGHT]="DEAT",
                [HEALBOT_MONK]="MONK",
                [HEALBOT_DEMONHUNTER]="DEMO",
}

HEALBOT_OPTIONS_SELFHEALS_en = HEALBOT_OPTIONS_SELFHEALS
HEALBOT_OPTIONS_TANKHEALS_en = HEALBOT_OPTIONS_TANKHEALS
HEALBOT_CLASSES_HEALERS_en = HEALBOT_CLASSES_HEALERS
HEALBOT_OPTIONS_GROUPHEALS_en = HEALBOT_OPTIONS_GROUPHEALS
HEALBOT_OPTIONS_MYTARGET_en = HEALBOT_OPTIONS_MYTARGET
HEALBOT_FOCUS_en = HEALBOT_FOCUS
HEALBOT_OPTIONS_EMERGENCYHEALS_en = HEALBOT_OPTIONS_EMERGENCYHEALS
HEALBOT_OPTIONS_PETHEALS_en = HEALBOT_OPTIONS_PETHEALS
HEALBOT_VEHICLE_en = HEALBOT_VEHICLE
HEALBOT_OPTIONS_TARGETHEALS_en = HEALBOT_OPTIONS_TARGETHEALS
HEALBOT_CUSTOM_CASTBY_ENEMY_en = HEALBOT_CUSTOM_CASTBY_ENEMY

HealBot_HealGroupsTrans = { [HEALBOT_OPTIONS_SELFHEALS_en] = HEALBOT_OPTIONS_SELFHEALS,
                            [HEALBOT_OPTIONS_TANKHEALS_en] = HEALBOT_OPTIONS_TANKHEALS,
                            [HEALBOT_CLASSES_HEALERS_en] = HEALBOT_CLASSES_HEALERS,
                            [HEALBOT_OPTIONS_GROUPHEALS_en] = HEALBOT_OPTIONS_GROUPHEALS,
                            [HEALBOT_OPTIONS_MYTARGET_en] = HEALBOT_OPTIONS_MYTARGET,
                            [HEALBOT_FOCUS_en] = HEALBOT_FOCUS,
                            [HEALBOT_OPTIONS_EMERGENCYHEALS_en] = HEALBOT_OPTIONS_EMERGENCYHEALS,
                            [HEALBOT_OPTIONS_PETHEALS_en] = HEALBOT_OPTIONS_PETHEALS,
                            [HEALBOT_VEHICLE_en] = HEALBOT_VEHICLE,
                            [HEALBOT_OPTIONS_TARGETHEALS_en] = HEALBOT_OPTIONS_TARGETHEALS,
                            [HEALBOT_CUSTOM_CASTBY_ENEMY_en] = HEALBOT_CUSTOM_CASTBY_ENEMY,
                            }
HealBot_GlobalsDefaults = {}

function HealBot_Data_InitVars()
    local Version=HealBot_Global_Version()
    HealBot_GlobalsDefaults = {
        LastVersionSkinUpdate=Version,
        FirstLoad = true,
        PluginThreat=true,
        PluginTimeToDie=true,
        PluginExtraButtons=true,
        PluginCombatProt=true,
        PluginTimeToLive=true,
        PluginPerformance=true,
        PluginMyCooldowns=true,
        PluginBuffWatch=true,
        PluginTweaks=true,
        PluginRequests=true,
        PluginHealthWatch=true,
        PluginManaWatch=true,
        CompressExport=true,
        AllowPlayerRoles=false,
        VehicleFontSizeReduction=4,
        CrashProtTime=0,
        NoRanks=false,
        ClassicHoTTime=6,
        CPUUsage=5,
        OptionsTheme=1,
        OptionsOpacityAdj=35,
        DebugOut=false,
        Debug01=false, -- Currently not used
        VersionResetDone={["ICONS"]="9.1.0.0",["BUFF"]="9.1.0.0",["CBUFF"]="9.1.0.0",["DEBUFF"]="9.1.0.0",["CDEBUFF"]="9.1.0.0"},
        CureCustomDefaultCastBy=1,
        TopRole="TANK",
        TargetBarRestricted=0,
        ShowTooltip = true,
        Tooltip_ShowTarget = true,
        Tooltip_ShowMyBuffs = false,
        Tooltip_ShowRequiredBuffs = true,
        Tooltip_ShowSpellInfo = true,
        Tooltip_ShowSpellExtra = true,
        Tooltip_ShowSpec = true,
        Tooltip_ShowLevel = true,
        Tooltip_ShowHealth = true,
        Tooltip_ShowMana = true,
        Tooltip_ShowRank = false,
        Tooltip_ShowRole = false,
        Tooltip_HideRoleWhenRank = false,
        Tooltip_MouseWheel = false,
        ShowGameUnitInfo=false,
        Tooltip_ShowHoT=false,
        Tooltip_ShowCD=false,
        Tooltip_MaxButtons=5,
        Tooltip_IgnoreGCD=false,
        Tooltip_Scale=1,
        Tooltip_Alpha=1,
        Tooltip_HeaderFont=HealBot_Default_Fonts[14].name,
        Tooltip_HeaderFontSize=14,
        Tooltip_DetailFont=HealBot_Default_Fonts[15].name,
        Tooltip_DetailFontSize=12,
        DisableToolTipInCombat=false,
        HideOptions = false,
        ProtectPvP = false,
        RightButtonOptions = false,
        HideUnlockedTag = true,
        SmartCast = true,
        SmartCastDebuff = true,
        SmartCastBuff = true,
        SmartCastRes = true,
        AutoCacheSize=20,
        HealBot_ButtonRadius=78,
        HealBot_ButtonPosition=300,
        MinimapIcon={hide = false, minimapPos = 220, radius = 80,},
        TestBars={["PETS"]=4,["TARGETS"]=5,["HEALERS"]=3,["TANKS"]=2,["PROFILE"]=3,["ENEMY"]=2},
        TestBarsIcons={["DEBUFF"]=false,["BUFF"]=false,["EXTRA"]=false},
        EmergencyFClass = 4,
        MacroSuppressSound = true,
        MacroSuppressError = true,
        AcceptSkins = 1,
        FocusMonitor = {},
        OneTimeMsg={},
        dislikeMount={},
        excludeMount={},
        aggro2pct=55,
        aggro3pct=100,
        RaidHideMethod=0,
        useUTF8=false,
        CustomCuresReset="6.0.0",
        LastSupporter=1,
        IncMainAssist=true,
        FPS=60,
        PresetColoursAlias={[1]=HEALBOT_OPTIONS_PRESET.." 1",[2]=HEALBOT_OPTIONS_PRESET.." 2",
                            [3]=HEALBOT_OPTIONS_PRESET.." 3",[4]=HEALBOT_OPTIONS_PRESET.." 4",
                            [5]=HEALBOT_OPTIONS_PRESET.." 5",[6]=HEALBOT_OPTIONS_PRESET.." 6",
                            [7]=HEALBOT_OPTIONS_PRESET.." 7",[8]=HEALBOT_OPTIONS_PRESET.." 8",
                            [9]=HEALBOT_OPTIONS_PRESET.." 9",[10]=HEALBOT_OPTIONS_PRESET.." 10"},
        PresetColours={[1]={R = 0.2, G = 0.2, B = 0.9, A = 1 },
                       [2]={R = 0.9, G = 0.2, B = 0.2, A = 1 },
                       [3]={R = 0.2, G = 0.9, B = 0.2, A = 1 },
                       [4]={R = 0.8, G = 0.2, B = 0.8, A = 1 },
                       [5]={R = 0.2, G = 0.8, B = 0.8, A = 1 },
                       [6]={R = 0.8, G = 0.5, B = 0.2, A = 1 },
                       [7]={R = 0.7, G = 0.7, B = 0.2, A = 1 },
                       [8]={R = 0.9, G = 0.7, B = 0.5, A = 1 },
                       [9]={R = 1, G = 1, B = 1, A = 1 },
                       [10]={R = 0.7, G = 0.7, B = 0.7, A = 1 },},
        OverrideEffects={["USE"]=1,["FOCUSGROUPS"]=1,["FLUIDBARS"]=true,["FLUIDALPHA"]=true,["FLUIDFREQ"]=10,["OFREQ"]=0.07,["OMIN"]=0.1,["OMAX"]=0.95,["HOTBARHLTH"]=0,
                         ["HOTBARDEBUFF"]=1,["FGDIMMING"]=2.5,["HEALTHDROP"]=true,["HEALTHDROPPCT"]=350,["HEALTHDROPSPEED"]=40,["HAZARDFREQ"]=0.3,["HAZARDMINALPHA"]=0.25},
        OverrideFocusGroups={[1]=true, [2]=true, [3]=true, [4]=true, [5]=true, [6]=true, [7]=true, [8]=true, },
        OverrideChat={["USE"]=1,["NOTIFY"]=1,["MSG"]=HEALBOT_NOTIFYOTHERMSG,["RESONLY"]=true,["EOCOOM"]=false,["EOCOOMV"]=10},
        OverrideFrames={["USE"]=1,["RUNBLIZZEVENTS"]=false,["HIDEPARTYF"]=false,["HIDEPTF"]=false,["HIDEFOCUSF"]=false,["HIDEBOSSF"]=true,["HIDERAIDF"]=true,},
        AuxTextPrefs={},
        HealBot_customPermUserName={},
        HealBot_PermMyTargets={},
        HealBot_PermPrivateTanks={},
        HealBot_PermPrivateHealers={},
        HealBot_PermPrivateDamagers={},
        HealBot_MouseWheelIndex={ ["AltUp"]=2, ["AltDown"]=3 },
        HealBot_MouseWheelTxt={ ["AltUp"]=HEALBOT_BLIZZARD_MENU, ["AltDown"]=HEALBOT_HB_MENU },
        HealBot_Emotes={ ["NoneUp"]=HEALBOT_EMOTE_HELLO,  ["NoneDown"]=HEALBOT_EMOTE_HELLO,
                         ["ShiftUp"]=HEALBOT_EMOTE_HELLO, ["ShiftDown"]=HEALBOT_EMOTE_HELLO,
                         ["CtrlUp"]=HEALBOT_EMOTE_HELLO,  ["CtrlDown"]=HEALBOT_EMOTE_HELLO,
                         ["AltUp"]=HEALBOT_EMOTE_HELLO,   ["AltDown"]=HEALBOT_EMOTE_HELLO, },
        HealBot_Macros={ ["NoneUp"]="",  ["NoneDown"]="",
                         ["ShiftUp"]="", ["ShiftDown"]="",
                         ["CtrlUp"]="",  ["CtrlDown"]="",
                         ["AltUp"]="",   ["AltDown"]="", },
        EmergIncRange = {
            [HEALBOT_DRUID]    = false,  [HEALBOT_HUNTER]      = true,   [HEALBOT_MAGE]     = true,
            [HEALBOT_PALADIN]  = false,  [HEALBOT_PRIEST]      = false,  [HEALBOT_ROGUE]    = false,
            [HEALBOT_SHAMAN]   = false,  [HEALBOT_WARLOCK]     = true,   [HEALBOT_WARRIOR]  = false, 
            [HEALBOT_MONK]     = false,  [HEALBOT_DEATHKNIGHT] = false,  [HEALBOT_MONK]     = false, [HEALBOT_DEMONHUNTER] = false,
        },
        EmergIncMelee = {
            [HEALBOT_DRUID]    = false,  [HEALBOT_HUNTER]      = false,  [HEALBOT_MAGE]     = false,
            [HEALBOT_PALADIN]  = false,  [HEALBOT_PRIEST]      = false,  [HEALBOT_ROGUE]    = true,
            [HEALBOT_SHAMAN]   = false,  [HEALBOT_WARLOCK]     = false,  [HEALBOT_WARRIOR]  = true, 
            [HEALBOT_MONK]     = false,  [HEALBOT_DEATHKNIGHT] = true,   [HEALBOT_MONK]     = false, [HEALBOT_DEMONHUNTER] = false,
        },
        EmergIncHealers = {
            [HEALBOT_DRUID]    = true,   [HEALBOT_HUNTER]      = false,  [HEALBOT_MAGE]     = false,
            [HEALBOT_PALADIN]  = false,  [HEALBOT_PRIEST]      = true,   [HEALBOT_ROGUE]    = false,
            [HEALBOT_SHAMAN]   = false,  [HEALBOT_WARLOCK]     = false,  [HEALBOT_WARRIOR]  = false, 
            [HEALBOT_MONK]     = true,   [HEALBOT_DEATHKNIGHT] = false,  [HEALBOT_MONK]     = false, [HEALBOT_DEMONHUNTER] = false,
        },
        EmergIncCustom = {
            [HEALBOT_DRUID]    = true,   [HEALBOT_HUNTER]      = false,  [HEALBOT_MAGE]     = true,
            [HEALBOT_PALADIN]  = true,   [HEALBOT_PRIEST]      = true,   [HEALBOT_ROGUE]    = false,
            [HEALBOT_SHAMAN]   = true,   [HEALBOT_WARLOCK]     = true,   [HEALBOT_WARRIOR]  = false, 
            [HEALBOT_MONK]     = true,   [HEALBOT_DEATHKNIGHT] = false,  [HEALBOT_MONK]     = false, [HEALBOT_DEMONHUNTER] = false,
        },
        CDCBarColour = {
            [HEALBOT_CUSTOM_en.."15"] = { R = 0.45, G = 0, B = 0.28, },
        },
        HealBot_Custom_Debuffs_ShowBarCol={  
            [HEALBOT_CUSTOM_CAT_CUSTOM_AUTOMATIC] = 4,
            ["DEFAULT"] = 4,
        },
        HealBot_Custom_Debuffs_IconGlow={  
            [HEALBOT_CUSTOM_CAT_CUSTOM_AUTOMATIC] = 1,
            ["DEFAULT"] = 1,
        },
        CDCTag={},
        IgnoreCustomDebuff={},
        FilterCustomDebuff={
        },
        CustomDebuffIDMethod = {},
        HealBot_Custom_Debuffs = {
            -- Defaults
            [HEALBOT_CUSTOM_CAT_CUSTOM_AUTOMATIC] = 15,
        },
        HealBot_Custom_Debuffs_IconSet = {},
        Custom_Debuff_Categories=HEALBOT_CUSTOM_DEBUFF_CATS,
        CustomBuffTag={},
        IgnoreCustomBuff={},
        HealBot_Custom_Buffs={},
        HealBot_Custom_Buffs_IconSet = {},
        CustomBuffBarColour = {
            [HEALBOT_CUSTOM_en.."Buff"] = { R = 0.25, G = 0.58, B = 0.8, },
        },
        HealBot_Custom_Buffs_ShowBarCol={["DEFAULT"] = 4},
        HealBot_Custom_Buffs_IconGlow = {},
        CustomBuffIDMethod = {},
        IconKeyCombo={},
        UseIconCommands=false,
        WatchHoT = {
           ["DRUI"] = {
                [HEALBOT_REJUVENATION]=1,
                [HEALBOT_OVERGROWTH]=1,
                [HEALBOT_CENARION_WARD]=1,
                [HEALBOT_REGROWTH]=1,
                [HEALBOT_LIFEBLOOM]=1,
                [HEALBOT_WILD_GROWTH]=1,
                [HEALBOT_TRANQUILITY]=1,
                [HEALBOT_BARKSKIN]=1,
                [HEALBOT_IRONBARK]=1,
                [HEALBOT_IRONFUR]=1,
                [HEALBOT_SURVIVAL_INSTINCTS]=1,
                [HEALBOT_FRENZIED_REGEN]=1,
                [HEALBOT_NATURE_REJUVENATION_GERMINATION]=1,
                [HEALBOT_NATURE_MOMENT_OF_CLARITY]=1,
                [HEALBOT_SPRING_BLOSSOMS]=1,               
                [HEALBOT_CULTIVATION]=1,
                [HEALBOT_INNERVATE]=1,
                [HEALBOT_ESSENCE_OF_GHANIR]=1,
                [HEALBOT_FOCUSED_GROWTH]=1,
                [HEALBOT_GROVE_TENDING]=1,
            },
            ["HUNT"] = {
                [HEALBOT_MENDPET]=1,
                [HEALBOT_DETERRENCE]=1,
            }, 
            ["MAGE"] = {
                [HEALBOT_EVOCATION]=1,
                [HEALBOT_ICE_BARRIER]=1,
                [HBC_DAMPEN_MAGIC]=1,
                [HBC_FROST_ARMOR]=1,
                [HBC_ICE_ARMOR]=1,
                [HBC_MOLTEN_ARMOR]=1,
                [HBC_MAGE_ARMOR]=1,
                [HEALBOT_INCANTERS_WARD]=1,
                [HBC_MANA_SHIELD]=1,
                [HEALBOT_ICE_BLOCK]=1,
                [HEALBOT_BLAZING_BARRIER]=1,
                [HEALBOT_PRISMATIC_BARRIER]=1,
                [HEALBOT_ARCANE_POWER]=1,
                [HEALBOT_SLOW_FALL]=1,
            },
            ["PALA"] = {
                [HEALBOT_FLASH_OF_LIGHT]=1,
                [HEALBOT_BEACON_OF_LIGHT]=1,
                [HEALBOT_HAND_OF_FREEDOM]=1,
                [HEALBOT_LIGHT_BEACON]=1,
                [HEALBOT_DIVINE_SHIELD]=1,
                [HEALBOT_INFUSION_OF_LIGHT]=1,
                [HEALBOT_SPEED_OF_LIGHT]=1,
                [HEALBOT_DIVINE_PURPOSE]=1,
                [HEALBOT_ARDENT_DEFENDER]=1,
                [HEALBOT_DIVINE_PROTECTION]=1,
                [HBC_DIVINE_INTERVENTION]=1,
                [HEALBOT_BEACON_OF_FAITH]=1,   
                [HBC_DIVINE_FAVOR]=1,
                [HEALBOT_BLESSING_OF_SACRIFICE]=1,
                [HEALBOT_BESTOW_FAITH]=1,
                [HEALBOT_BEACON_OF_VIRTUE]=1,
                [HEALBOT_TYRS_DELIVERANCE]=1,
                [HEALBOT_SACRED_DAWN]=1,   
                [HEALBOT_LIGHTS_GRACE]=1,
                [HEALBOT_GLIMMER_OF_LIGHT]=1,
                [HEALBOT_BLESSING_OF_SANCTUARY]=1,
                [HEALBOT_BLESSING_OF_SPELLWARDING]=1,
            },
            ["PRIE"] = {
                [HEALBOT_GUARDIAN_SPIRIT]=1,
                [HEALBOT_PAIN_SUPPRESSION]=1,
                [HEALBOT_POWER_INFUSION]=1,
                [HEALBOT_RENEW]=1,
                [HEALBOT_HOLY_WARD]=1,
                [HEALBOT_DIVINE_HYMN]=1,
                [HEALBOT_POWER_WORD_SHIELD]=1,
                [HEALBOT_SPIRIT_SHELL]=1,
                [HEALBOT_POWER_WORD_BARRIER]=1,
                [HEALBOT_PRAYER_OF_MENDING]=1,
                [HEALBOT_ECHO_OF_LIGHT]=1,                       
                [HEALBOT_BLESSED_HEALING]=1,
                [HEALBOT_SERENDIPITY]=1,
                [HEALBOT_TWIST_OF_FATE]=1,
                [HEALBOT_DISPERSION]=1,
                [HEALBOT_VAMPIRIC_EMBRACE]=1,          
                [HEALBOT_SURGE_OF_DARKNESS]=1,               
                [HEALBOT_SURGE_OF_LIGHT]=1,                                            
                [HEALBOT_CLARITY_OF_WILL]=1,                                      
                [HEALBOT_RAPTURE]=1, --Disc
                [HEALBOT_ATONEMENT]=1,                       
                [HEALBOT_APOTHEOSIS]=1, --Holy    
                [HEALBOT_DIVINITY]=1,                      
                [HEALBOT_SYMBOL_OF_HOPE]=1,                      
                [HEALBOT_BODY_AND_MIND]=1, 
                [HEALBOT_INSPIRATION]=1,
                [HEALBOT_HARMONY]=1,   
                [HEALBOT_SUNDERING_SOUL]=1,
                [HEALBOT_FOCUSED_WILL]=1,        
                [HEALBOT_LIGHT_OF_TUURE]=1, 
                [HEALBOT_BLESSING_OF_TUURE]=1,
                [HEALBOT_POWER_OF_THE_NAARU]=1,
                [HEALBOT_POWER_OF_THE_DARK_SIDE]=1,
                [HEALBOT_ANGELIC_FEATHER]=1,
                [HEALBOT_ALMAIESH_THE_CORD_OF_HOPE]=1,
                [HEALBOT_VESTMANTS_OF_DISCIPLINE]=1,
                [HEALBOT_RAMMALS_ULTERIOR_MOTIVE]=1,
                [HEALBOT_SPIRIT_OF_REDEMPTION]=1,
                [HEALBOT_RAY_OF_HOPE]=1,
                [HEALBOT_PERMEATING_GLOW]=1,
            },
            ["ROGU"] = {
                [HEALBOT_VANISH]=1,
                [HEALBOT_EVASION]=1,
                [HEALBOT_FEINT]=1,
                [HEALBOT_CLOAK_OF_SHADOWS]=1,
            },
            ["SHAM"] = {
                [HEALBOT_RIPTIDE]=1,
                [HEALBOT_PRIMORDIAL_WAVE]=1,
                [HEALBOT_WELLSPRING]=1,
                [HEALBOT_DOWNPOUR]=1,
                [HEALBOT_TIDAL_WAVES]=1,
                [HEALBOT_ANACESTRAL_GUIDANCE]=1,
                [HEALBOT_ASCENDANCE]=1,
                [HEALBOT_UNLEASH_LIFE]=1,
                [HEALBOT_ASTRAL_SHIFT]=1,
                [HEALBOT_ELEMENTAL_MASTERY]=1,
                [HEALBOT_FLAMETONGUE]=1,
                [HEALBOT_FROSTBRAND]=1,
                [HEALBOT_HEALING_RAIN]=1,
                [HEALBOT_SPIRITWALKERS_GRACE]=1,
                [HEALBOT_CLOUDBURST_TOTEM]=1,
                [HEALBOT_EARTH_SHIELD]=1,
                [HEALBOT_SPIRIT_LINK_TOTEM]=1,
                [HEALBOT_BLOODLUST]=1,
                [HEALBOT_HEROISM]=1,
            },
            ["WARL"] = {
                [HEALBOT_UNENDING_RESOLVE]=1,
                [HEALBOT_SOUL_LEECH]=1,
            }, 
            ["WARR"] = {
                [HEALBOT_VIGILANCE]=1,
                [HEALBOT_LAST_STAND]=1,
                [HEALBOT_SHIELD_WALL]=1,
                [HEALBOT_SHIELD_BLOCK]=1,
            }, 
            ["DEAT"] = {
                [HEALBOT_ICEBOUND_FORTITUDE]=1,
                [HEALBOT_ANTIMAGIC_SHELL]=1,
                [HEALBOT_ARMY_OF_THE_DEAD]=1,
                [HEALBOT_ANTIMAGIC_ZONE]=1,
                [HEALBOT_VAMPIRIC_BLOOD]=1,
                [HEALBOT_DANCING_RUNE_WEAPON]=1,
                [HEALBOT_SHROUD_OF_PURGATORY]=1,
            },
            ["DEMO"] = {
                [HEALBOT_DEMON_SPIKES]=1,
                [HEALBOT_BLUR]=1,
                [HEALBOT_METAMORPHOSIS]=1,
            },
            ["MONK"] = {
                [HEALBOT_VIGILANCE]=1,
                [HEALBOT_ENVELOPING_MIST]=1,
                [HEALBOT_ZEN_SPHERE]=1,
                [HEALBOT_LIFE_COCOON]=1,
                [HEALBOT_THUNDER_FOCUS_TEA]=1,
                [HEALBOT_ZEN_MEDITATION]=1,
                [HEALBOT_SOOTHING_MIST]=1,
                [HEALBOT_RENEWING_MIST]=1,
                [HEALBOT_ELUSIVE_BREW]=1,
                [HEALBOT_FORTIFYING_BREW]=1,
                [HEALBOT_DAMPEN_HARM]=1,
                [HEALBOT_DIFFUSE_MAGIC]=1,             
                [HEALBOT_EXTEND_LIFE]=1,
                [HEALBOT_TOUCH_OF_KARMA]=1,
                [HEALBOT_ESSENCE_FONT]=1,
            },
            ["EVOK"] = {
                [HEALBOT_ECHO]=1,
                [HEALBOT_LIFEBIND]=1,
                [HEALBOT_DREAM_FLIGHT]=1,
                [HEALBOT_OBSIDIAN_SCALES]=1,
                [HEALBOT_TIME_DILATION]=1,
                [HEALBOT_RENEWING_BLAZE]=1,
                [HEALBOT_TIME_STOP]=1,
                [HEALBOT_STASIS]=1,
                [HEALBOT_FURY_OF_THE_ASPECTS]=1,
                [HEALBOT_EXHILARATING_BURST]=1,
                [HEALBOT_ESSENCE_BURST]=1,
                [HEALBOT_TEMPRAL_ANOMALY]=1,
                [HEALBOT_TEMPRAL_COMPRESSION]=1,
                [HEALBOT_NULLIFYING_SHROUD]=1,
                [HEALBOT_CALL_OF_YSERA]=1,
                [HEALBOT_EMERALD_COMMUNION]=1,
                [HEALBOT_DREAM_BREATH]=1,
                [HEALBOT_REVERSION]=1,
            }, 
            ["ALL"] = {
                [HEALBOT_GIFT_OF_THE_NAARU]=1,
                [HEALBOT_DARKFLIGHT]=1,
                [HEALBOT_STONEFORM]=1,
                [HEALBOT_SHROUD_OF_THE_NAGLFAR]=1,
                [HEALBOT_SPIRIT_FRAGMENT]=1,
                [HEALBOT_NORGANNONS_FORESIGHT]=1,
                [HEALBOT_VELENS_FUTURE_SIGHT]=1,
                [HEALBOT_SEPHUZS_SECRET]=1,
                [HEALBOT_DELICIOUS_CAKE]=1,
                [HEALBOT_GUIDING_HAND]=1,
                [HEALBOT_FRUITFUL_MACHINATIONS]=1,
                --[HEALBOT_OCEANS_EMBRACE]=1,
                --[HEALBOT_AOF_INFUSION_OF_LIGHT]=1,
                [HEALBOT_CONCORDANCE_OF_THE_LEGIONFALL]=1,
                [HEALBOT_HIGHFATHERS_TIMEKEEPING]=1,
                --[HEALBOT_TAILWIND]=1,
                [HEALBOT_BRACING_CHILL]=1,
                [HEALBOT_BLESSED_PORTENTS]=1,
            },
        },
    };
end

local defaultAuthor = "Monti of Terenas"
HealBot_Config_SkinsData = {  
  [HEALBOT_SKINS_STD]=[[TR1wVnUTs43ZVIK0x1gyjF)b)a1fBPZAl5kkNnzlAaCt8URrtSlSDkApfo)2pZWH3KITt2MDXjTia7glro35hjhou8FD(IJ4BMU4MPRU5i29B(YYvp87NK87tx8LLl)0XW)kMTA2IPRpk8(F725xpDZm)PRwd08PP3UE2rbFz6Mh2CYFfLfKLnQ3PIwp1HE98EE1CgXh070GPR3mFXNp(hwF8Yfh)dlo1jpINLo8YENUz19adPzfj9VSxTThny2IzRMElk04KWi)moVVwUdgM5ZggMmAus6GEUoXzf(S84HfX9Q50F4KKq4vUsOXSpYYdbszdhhZ6v7mVMoOmhZYlU0i0yFLaB4ehXaHfMNnMpokkSxJAofSb8cwrukBuu)S0cT0bjLZsc7RAidKbOexYq6Nh9J9CBrVqgGsH8IKG3Fz)CqGLnvbp1oRoik2fWdDBAzqJdk6vVznNmjvUUoNh07u3ANv7SMN15uN(zbt4dYZMmMJHg0rlmEz)bkV07SMotstkssdYg5Zk65jJJq0Es)(iVALAcsG4ekWiX8jP(dt(4hJopkTGRAE7rXZMElmyJJGf4yC)8KO0qJHeDbg2mVJs1YweEW4Oc9WyblFqKT1w8ij8yTWJg2heIXQIwm7U)eTjLG4XzFGLddRGdB3gYjOeOjQxPvytIWKbAIUiHlAOGL(EIhnndHUSjHewDNO0OrxsUep5JricZQjZmifFKUeMOGOhtbofrzL6gjAD1UbfqLScnIwSMR0jJecPHH)Xi71rkfXdlojdsYzy2e)HrFijeMbArJokicmUBpQ)YRVF9GvlV)3wJJbsU)A)bKZQP3nJD78PRF4tp4EYFjcHUEoPI5saMeCz2WegyGcsp2fw0aAdTfTbM1Vphc11COPZ9xn))E8pE)0BwnDZ0Jlko1bHe(W)ZMummjns4a2k27zOyVVhkU(ZqX1)EO4gpdf347HIB(muCZVhkUvvfF(SVm)6BNvs)62(2R)2v1)4zBwxs5udF71CNQAUy6QppBtjDRA6BV27wv7ILokpQtT8Tx3U1QQCXUgLuUSLVXkhsQIwqdttPbqhMhHuKVRbOF894OKbXfysv0cU1oRnyh4FHDelMKd2lU3R)Ynh7w70QI)Mt8EO(dnEO5dTEO9dDEOl4Upq0qQ2Nf8Esr8(KQphCh1Zygw(zqoc5inEyQyFa2GGAYx0e9mZ65bINlsgpmlOxthudKRHpHewRPdpGnmcJVtkYcgMXXNXUhiiey89qEyQGvfVqB(D2T5)UoV(S)Uwb9AV6J68nZV(x)tHbR2YTysW7TYLfERiBCwcI6tZsJ0THUb(KDFpsGEAbsB0xwEWd5iM3it3sYe6Fyu)Ihl26huS(zffzJeC(1k4gFBda3CccKRQK2FVS(oFFI2DpOypOm3TafleFqd9jCFsN0zrKPDkaV0HUqYHt0PhdP165ZU9tvzX7WSmA68fhdhF(xxxLX6hMrK2zREexnomxc6QYtZhXJmPEbl5tNFtvoADyTmE18FhoN)XdNVEtvwBRyT(UuMkDOkm15GmjsJPchDvC4TloKjFuD0T2bzIsAOkpgirTDXeTz)2JylU(llxjXqx2RD3ZA0bpO6haDjQ4qDhLhErpp3ZQ30MhVdZJ7U4PUGhxSea7Jh3wN1STnpnqEA2EVgwzQBkOU7(PURn1TqQB5UxQB5AtDBb113RP3QUn1Deu3C)YUuKPRG697LTk5LiQ4PgWKbsazCJopmk3oclyYjZZH2gwMjMBtDMy44KGSDNkMs27ojmS3Iz)XgtkGTBq5kQsQmVNo9p39NI5GYPxQf7E16TA)vk86y9xghKn0uSGGrS8bjP9SCn(DlxU5lN6mo7dr5bMsIbjNmILYKfQPCJqGpxkjpWVsGWow3bHQ8KHrxVMB1M1UnAONGL3QsyLYosKzTiZh8bAyior(l9twUCqmlpOq9KmR6GbQgKHBH0OeHct4mk1jGrFrU2Wtjf0tsof1Feea1FCIKod9zdzJ1v6tsvqUsRItCiYDZyjMEfstKXxczs(jY(GS1qt14pskL8glTYyf9YML0hRnVjialweevSy0EUuNsIPO6w1WWEhJsy6rjwamjJHOzMaz3XjjHMlLeqZMyiUnbjt1bsyhOJerjSWUzsZMfiAkGAtivrdjsrrel9JKaFzRccfmLO6lxAdKCtqg3Am996zM5P4WEwQpwsovHkhKLbVLD)gSY55tx8zSCydsZYJYs7pz4qD6m6j2XJyxeeJRivdlCgw5vC(ak7IlkyqlGeLVF5yXw2eVEad4MuLSaMwU46xaUtVFghR6nS)gmFdxK48OCuv9ZG5KyzkzMfxW6DpzewOffvepXg9chfEaonginhjm24ok5i6KnawYflolCweRGuEeS6s(S13VA1SR3m7gJMa1yfpqsrgdH1XG1HgY4CP3QlYl5us3OoYryaWW81xVCXcPW56LeH4J(r(tVCASHAZtWAwK68q5HoOzCQUPx3EUIt0TNAbSVoux2qLGggBGfFZz0qHGeJADvJ74yJEnmSYV(CyvbXTba4NK0ZJIf12Di7YinMXWQkIaKVh7BR1maV)1pdGF)D3TCHn(8VZmHAVnt4)RZeQ9cMju7zmt4Mt27(e69a5CRnLBtWwethi2nJhi2zkL6lMEJlPuXjlie3vSPdpxURwmrxU8NiZ15qILfqjmWPxtjcZcOT0zbunH45YDH5IDlLBkdKlOoMyL6ItMPIbwGubXu3PI)MjLBCK4vwIspIxJL6q2MyAMUqk4XV8qpMsdkf2AUbO1qP)YtKHjPLj6fIwKwfTfPOqKVSKEl(ZLjhabwBvBf7YTGAY7dvF64kVlG84khslbZc0dvhv)nULO4QbV4agDyHuvlm5OtGmgsz2invn1IO3z18Wbtry1knOynYGOQbY(a5GSmsNQanCzqLcY1WJYGdNOztMHuJXjsOj9xzRCIkUYhtXx3Ad33DEtjWIqYtpNheLQclIfYWxLru6oqn9JH7(SqtbkYdo3uuCyNMZlTAVqCveMIcp57uDpfrlGJWeRLqX9lckFPZYLvAbk2WyEGzvEIm17VZdoPwGEjqH9OmG6cVHUV0k2iTuoDFcQZojj4No9N(lmcWJc4)8P)mEIZkbeBMbCCbEd)67Kao2JAHr4zfPWJgpqyKsQOGsCgiflJ0A7gxvuBu2eEfkuIeIbGckhNT3hg6Sccqt7wjqz3GiSuwy)YLu)XjSCTqdsYdmQimHnkd)yaKZ(Sol)iyxy9yCEclDGvgcfM8i4V3kzLGCZvSV1yh7hRBoKaoOZ5HtYlnKsTcNCghtT)Kfs0w9wJG27zroF(65)Y8BNV5pLh1AyuEbCqk8YQGNYcuZLdJePLP(wikZ6EfpF5kPxWNOpFniiymZGqXVedQV6WAQ(J7RTFLe2R8zF(ZRwkdtYACGdvMya5gSq40ZIV6JcD6n2dPde5HHEoWONOlKwvuON3wJY2TTWU)pakSUkmmlmi1aAfE9SjQXs7biBlpcwvRGsDTCxJL5Acefd5umuKxrfURSVISvRrmTeE83LJSNYF9iBl5r7bMU4g8Z5sxvZX6mTz8XSGiX(9zuEO6KRW54I9LOKVoNELRjyKOwg1Dgl6PMZiXVVdKPfjcP76m28G47GXzmj1XXeVmPS4YUhjBNRmcs21Dgj4BRTh9yxUI)w7FUoSN2HJUB2QpRQzORJCpF5o(6DHcPRgeR7KJz)YG8eyLc4CgIVkoyTD5XIOmjeL5PRU4M6ApksHH67rfdKYiHuU9MdjP)hGUqsU5cEX6l5qOEPMveVJM0BvPC4dnh(kxRVliqvDitjfoghDl(GKZMKl)g3IY5yPjPpervwD6nmLN2CGPoSUcV2yS4Gc8F8dTlg28SQS2AmQdzZ4A8k7ENl8yDqqW8Lj7T3fvasKwUEWENlsS3d7bcGrXUhfCGU8nvIUBPLHH(gywSB)RiEGvXkTKN5OQYZydki3C6Bepuk(DqyH3RryH3tdl8Edw8IGfhoeFv9xJWI6pnSO(BWIxeS4WH4RA8Aew04PHfnEdw8IGfhoeFvZxJWIMpnSO5BWIxeS4WH4RA9Aew06PHfTEdw8IGfhoeFv7xJWI2pnSO9BWIxeS4WH4R68Aew05PHfDEdw8IGfhoeFv3xJWIUpnSO7BWIxeSO7bUfb(SnRvfgkuDlq4vafAQJNV1JQ7rPHOmA6YBgwU9kxb1JUJnQUCMYxYUimjilf)Mm8nxBuO1Jr7qSHjUnnxZdrI6oKQ(Czslzm(cvJ1nvuYWsVPSCvubSuI8En2Ah)oCa2U6B6RLX4g(CRVVr4nXn5yUDsnIk0h6PiopgEw4FsyGhfZ19f6BXYJi6dS8u5nfsO88L)YYnlpE0SBMF)DNsAXIOY3SuO)ozsqOLxiE34hBRgkEcaP3xpGSPnGSHbq28Rhqw)FKasVT2XVNbG07RdqAf6(3hI8PcyQQH93gr25fHiBBHiDniYMge57A(kes6U1oa(mGK1FdsAfl2Daly5D)2TZ2m7K)h]],
  [HEALBOT_OPTIONS_GROUPHEALS]=[[TZ1YYTTXs796PqwNTWSWfcsIfCXqaqc8BsagaqzjVqvXyXyRkYIPKOZ)XNuup7NU75kGiiftKCYPkViwaZLU)6E(Mz6EgWu(R3C3jtUF9x)TtyFDZNxF)J)(BIw)X1NU(xoD2n3V8tRoTy5hx9)V8BNe91F72B(4YnRgT8(hGM9llV9HvNe(5LBECZB(J48W88zdpJk9ml(RNp012Aw5KHNfU8Hn3C3No9F9WPRV70)1DNzvexMNn9YHNT5(VcDimHLn8SZSYYRshF5qNTNmz1DRUF5TOWtsJIhLxwowj)jtZhXMgLoBwA2KHowj5vJyfjtRsgABvwLg(UllJZktRsppTcexG14PlsJG2uk1yc7dSIiO)SPZtydT746BHkAoRO6sTMgNhUOCsr(I5LOEIzGoIkYNxopooAONTvfBszfRkoJnlECEwLQNCymUakxQZCqDGMC4OzCr8pn0XM)chfY(MmsABUDCfqLAUDhpcLeS0OuJR5HvdD8TTkwKnAA6h(q85XzvLQgEE4WZCS7y3XVd8hNZiHvWaWOLf6eQm8at0yPNvUag2bcNom0Sy84A(gvxZNXUaA7aFRfzWyrwy(SrSQHUBpjz1YBbcbo6EECsA40yvTYoJTVmEQbqytFp7YYYK83Rjc4iZ84k1WAfRysSwvowZlspFAAzf2iTo4nEmsbhxKgNfPkk(c0DOrHztmqgPyTCGrdT5bG4Pifnfad1esT3BQyOEEbKo2Es8DR(Y3qhMurO4zfaXd0y8fGjIfm7sWdaMn0iEDs5z2lcVM9QIL9oOtQ3XzBsJtvOuxMsc9SyhZIjfpXWGu9JRncsC0zajsM8XpDHiA0Qxl6Y0pep0BqnaqmehRSfZim3vR25OQi0wJfbVZbKq(r5lgnn(9PrWAh7YxrUgVTNmE9h)6d0sLpGdcIEFS)bKZ9l)Yk2T3S8Hh)LhDEZFqgLJRvgToX8L3V5BWQJGjXMMYausQei6qj14t5JhxcEBBl(IoJV)M)ZP)0xxE99l3S80QQZSyqpgb)x(IQPPzX4AQ10TBtDxT8UF90L3D9P4KZv3xdfvlV)tR2q1soIxda59eNXQnpudfzR3C6IhwD9PoVg6VBt9twkzZCZF3yX91al(nXcn7F3aW71aa9AcGA6(8vF(MpE7Qxdf3)GSaEbV8AEWtNq8KrDzrV8ApyVo8xTjDo27vVcA3lSEHqi5l(jI7IV6RDNaPCFBxOZyGsjXPtsQW4ilO3Nq)lSxz1IcaRr3S8tRVB5TN1u6x)g3h9ES7J(p27X(po4XaWqFK3gUMhLdrUuGc12pWAel8D4ZUGxaFgvJR9ayt45tZdh23AolkIhQje657h6zX7)iz)P3qBUCm3eoh8nSfv5HtZlJrFbi1rKg6rptTnKnLQJ69eHSKsadLfu(7GWmD3QGU7FvOFw1Ay7KAW5WGVUX(mHV3oGpSgFnax3uQjitJrBdsr(IAbkFLPVx7TKW)63GekLT077MT49YBl0cT)V7qbTAD7W3uF)vNiyA8VCtec((aF)xa4VRLHWTnErwh67WYOMU)Yn38XF9BKviJ)UAr47msAhERkFEEkUTwwEwSQm6KfGNmR7jc0vjqEu)1Lh8W04XvAr6utKq1f42DpvSEVS4uSqwdL0BVyFuEvv(SdaFQ6NG((7h9kZ(yL7Gdk39bxdd6jUNGN4CO4K(R4D4Tqo(IPyjsMKyH8Jjc7bRsDCr84XMT8M7oDdKB2dn7N7E7x5QB)LM9WBV9GNQzJU09jDr4SfrNF)n)(YnRoD6npSPzx93Fx5Pz(eRQ3(7vXYBUUzx6l7sVD2fz2kn61G96mOSmA0JazpC3vpe5g0CW1EVDIhyFZ(Oze27Qt8OY3Ec7Up(513lOqxoSNBh3a8iXEpTPCrjS0hxmEwxmmWVJtFZ(4(m6detUVzFO43Ogrm5Hbd64BbZcq54bHeata4LDPOKl4VYz)IYKYNRvtX3TP47sc33fGHq4DbrZF)c8fHG5L0UG9Bi4bD747qYU7GobECzZl8srrxiExObEHTRHEn0GB)GED6oWX12XPVtaPlh7God61lOV3G(9KwKBV(Uyd7213ZXf9C(WgyO696y7kv)Bdc6445z75133TB395e73ajo22CVy)od4QelbgGCG3bNiWauQHAt7IEqZXNED6XDJ9gGjYXhIOcVuu0fI3LmaQW21qqZbkBWJXhO6Qyy8cVuu0fI3LduD3phdNqE5qpNo(D3jVVRM3dtkVwLRAT8F1zSIrJ4B3JYpf)RmJ1bwyYTDPmwXY3voRs5V7SvXARw9V3OtvUpPTb6SVPaUAnhCbuG1qMW7MoxCLSBv13QmCHy88b318W8P6ZQnCgRysAgEI3sRR8lRxV5ZN(7UNznp)9XfHzQtBhI6BglJv)i4ffYpcxs4oG5LEb8NcH09eEBhh7TkKH42aMEFNGP7rdtkslnq79kdufgmWLaOAKRC6Bnqw))jHmxtxiYknPK2Veiv08xesjGRW13koyP0j8RhdshHPYkz4aRKWkAbHeS0Kj8J7QGwKa3FSqun(eL7uFOv4tyjIj8K0KvgLwYOCDOUmsuk8CAfFPIqbqORffwKBKcxPszmkuxy(uM6cTsiXb6hxGjiGYTSqcQ0rCqfwyOtL(rZa(3cHCHC0gIxzPatsFJWZmsjt8mhhj6ucHVbbOpJRRfKTNkfkknRe(IFOYvajvBo8d1un2S715GktzQHogP3E99Ty8vBtfJjmmR1uQw)bdSs51wgkmQMJDq)WM6X9B0iD)EYrjJrig1mFyZCgnoGpjhD6fakKSMEioilhYMM7NvE)a3aL3h6bJ8eKbqvtIMxjug3nbvjmQc9yGJpOeU7ThIlytqMaKPCkcQBjSXZ1nnKFiOCncGLtOL8KEEB1o3w996D3qoAE2i8YbL3J7K8C4n4FodeEwErCE24ftNQt2tTlyYm2fHj4E424v3HxenUDokZQlQyqj54nbsVF5CmEF2eyNFDDEO6IcPpabieGAaj)84cuIJZHP(4L7k3f1LorCyAtSXD8oNvarRdlzGNCdBs5IzOqz6DI5G2fqQuWyJbWPRGnfSx6wKNuG9gBeSuwbJl2ePWinqwcEh1vPQzV49QoQegzrVGunqpnCtcFNNv4uwzPWGByfclgCKAtgXuCjztM(bbI6kcfPy9pVEZ6tNT66B(6xOXYceDyN46L2gLlFxC4qA8V1PVUgh0elpCWnYVaJgEHsUFuKCNEWg8GspmJ)GN07JqPv9bSN0SZJtO7wEk7YyffP0WvOhgtArsBny(UhhZxQUDr8vJOpHBBW7BoLWaU)9q8DocIFRdn)5NgySAXpMiuFIGXYmppQVAj0dt8V(nTUDGAZ4YsAlSUQyhY4NHswip8ixCdy6rN(EwzIgLiQ1kJhseUXwI4tusoSYcJWnW9TkfHnXJZc29Qe3(g8t0iR4axcfB06l2Ug3kNdnsjYIYd5xqjtP2sraswLITq9deBKdHvkuirBrJIAcixEIA8DVHnrHN4Hs4HXqXBdVr2W8Xq5DKsvW4QXnOlihEEIjc7lv0YsAAP6WsXZvc0TsGzIidkJe9RKhitaegrwk5AKbXkJoa0DbUqe3Wc6gyvOjEjYUhyLziYcHilvryqo9OqKsMZFH719DDrnWvSuagMGiYwq48b9sdLxkhLtcPa55V2xetlXJgj4rzIIseJ1GxhBBGp6BgXDj8wB721YGCukdPxk8sz7zCtht8NX7koewkbklKm2Sc1aDMKUNX9dzeQzP8xeoTb4DDWrMmkUSgK7mUvTT(8j3xQ5tUV2ZMC(XmPFmt6p)mPx15r7ABR0pU(oXbWxegNPShmcj8lhu95CsFbJ6gueEUyR2UwqKENRIPthBL5h0QSEFX7878Ko6aSdrPgrTGciSE3vXcwek7Pp8SA3(EI2LOuJr4qo8xKqWXJubB87QzSXLv4T7AIIgFqVurOKA4uKAPiu(e4qsuoe4fvalWZY2GsljhuQ2vrcx0wFXh2P(CHWkr)V49IqLtr4bNLVOu3EqvAxf15AqYqsuLQbKTckXUt6fV9kSErmo)0cwHg(PfHAJjkLnlx)DjZp9zXZVZiBGQIuw2eD)kR0HWpdcjwj9c9307wno2nmXQ0jNlTT((40sZpX9YOff1(cNt1FM0B1sP1da48BE4MF(MBVzZ34AcIhNpovsFcAXfvPHI5P4l50l0xOoLIKur1LuRARC99slAH4y5CXXsqJABc)MR51beJfJMpw5ZKsOv5Z(0NUFT48mOpzFLqPnnGSc4R(mGgnnCvCRJfXMlo2srgho1g25(Jm8lUHwr0NZCX2l9wd5lyjbcSTpDipuUvQo)Su2eXsrcPVtaxtB6fhnrqFeb4ay))KOW54qbDfvFhT5G6d82V5pmu6iH8oIrAjjCOtt0O0o7R)BqLgFkJyQTqsz8iGmsEhkJVLwTIkIHTPQ4z9QwRJQcHKOrjqQFtP0)Q3KlL7swtKn(W)LYW43dsTMttDfZPmnMwwk6URXF2rQR5EU6WlyLZzHXuWE5886v1GlvJ)LxbT1f(tbHotyFRzI)oNk32Ag9xier1(mZ4I2d6c9aucxuZfhfbjHUw0EcOgO37BnlHlXsLKysDZRzRP98udUH1A)CmxN9BU9fMB)gM7BDEQ96kTxBjELgS0qzczPnqLjlQHBWV1t4X2Es8xwD)NK3Hjelb)t4vehTqm9SIK)eSWjn6OHclsHTayt5N6nRaLzx5TNioZ5Cr0PIZRaLcssfTwUDA8tlJIjuEtUqV21fgLM9)bffrXiMkYsaJtpLhFRzedjQpEzpPvVJryL7WEp(dpH)yFUdFP)WBV(d8rttxa26(dzKmMoeNM(dtNH)Z1zylNJFLJ5V3fEBZwFNCZrydcaj5lke)sYIlkXRGJ)BeuU2PKZPYPJUxoHVHwNuTgK4apL5yI)K2sWZiRPqnG3Ux)HxnggJ0cQVERqHghQiyhreYABTuObe880GF3RKUZdre6nJp9VU3bkF0q1xmFG(2(33k)Yda0CP52xgxRjCJz4pf6dWvpsl8v7ZDELB7KbhjrW7WeHjpzCxmf0XxmK3Ltse(Bkvyi9XwzbUhMf4EmSaCMYb5boppEWtp6xIkq5Z(pC2W(DRx51EGmnwNW1xTg5UcwreNH8mSLd7pX7uieLGP52ktRg5AIOxIftWJG5dgEuDCnwMt)BlmOAda7mEQAXiboPdsn9EHxGY1Wv(sVafELqQ7o4Vdo5(9Nx19zSc1b3QYJYGzNRq5kOrEw8d8sVeLt7lp19WCGU)y5PJMkSF36v(VeuHUppQGZZJi4FyIG)pichnry)U1R61grO4iic73YAJJ44Q32rYqMi(nw2klP3Hzj9(bl5Ozj73TEv)9KOZZo2wV2JTvgARpTZXa)Ar32pWTD(q)dZh6)d(WrZh2VB9Qb7nXxB3NnNG)XKt)O6osEXEwJyWH5ed(bN4O5e73TEvWlrifohoKcy3cDmfUnyc1ZViW8)NG8Qajjky0r4yKhvRKZGDENRgU5GFqnpAQzWEU0VYvBEqEoxrJzrXLXHL4LPEUkqeRr6ZJCK8Qb7rNXOkZ8iJRmmk1XxFV3yZq5w)Cz1NMm7IO0W8m8)t(GviVexrJ1xblVF1RwkBjMPMiVV4MpxdvrMqAeba8CWjsQXBGbRraavElh2BRPVB)oxZdseHr9lunAuPXpJc4nZ7xLAovGSA4LQKIeGrrwNkDAY1uRotXIVRtcx023ZkWV)poKm1kPfJA3zk)rJAPyTEIgPW32MEJdWhDBYhDmiKU7Kp6BYh7Q5JhfD0ZGo6wJok9nTXhngXQb6JMrkfuns4ZGsA4JB9W3Qni4(pfkzW3hgzWEiKhYHjpNTdsiHqYgzSs4XsjRDvnIo23Gt68AYjDFr4K9BHt6Xd24LYdUh7854gBmaOb)o9Gr7qS7Y)zms00PVxFxt3U2dAxZd22NJMIh79pMTzC)7FsDBh3B46V8B3UAZQ38Fd]],
  [HEALBOT_OPTIONS_RAID25]=[[TZ1tZTnoY(75tHJ3RmQ4FfjpOdqKuICJePgskN4zRxQsBSMexJJ1u2kZBZBk7p7VUBaqasrjzNXoBo4dteja6U)1)qdGga0t1VF51VQC1LxCIT3RyFD7N3CZ9)5RJ38XnNS53oz(L3S6tRpPC1hx))U6BVk(R)Xvx(XvBxpE1n3cn73wD1TRFv0NxT9(TV(VskIkkMp6uQ0tn4VE2iBtJ5vthDA0QB3E51F6K)XTNS56t(hxFQrzsvr(SZhD62B(kiquklF0PNAKxuNn58rw39QPRVE9nRUcvEAwCY4IQQjn6F6SIXSzXzZNNLpDKLrAr9ywz6S60rMgv1zrV98QK8QS6SZYQb1fAmz2YSyOnvslMY(vwzmipB2Iu2iZb(EgOHwWkRpxzPjfrlRMwwSCrfANegyJ4YIfvlssIh5yAuZMwvZQtYzZtMuKx3ijhgtkHYL2SamhyjloAMuM8lJSm5VWrHu20XsFZEGTaQuZnhmKqjblfkv4Aru9ilptJYL5JNL9R)AYzj51vnn8SOrNAzoa82bwNsAQKbirPiKbQ1C)PkGm0OqGbZqbJd9llNmPfX0iAXC27H2g4zSmh6iYJkMpMvpY5UxLUE1vq0a21ILxLmtzqSaesskJO(fj1n9B1SYPjk1zrsqTs2IjyG1KYSK8yvraD1iJTrTEtKUkB27yNxvLw8UMYwuMD2SSQAeanI3aKDBpIfOTQyaW10FVo59CNtAZ2VF3RsUE9x(gsmsRHQNvcrxaQ1lJinlSiETsnQ3gYRb5sEp4cyb1S83YfQPnO3P3ePTAkah4jD5K8K5NZ7aud1LnKBns7uJ2Tf8IvGM3TkBLs3vz)AYiNaSDiIBmF(Y5eACvQCbQrIzAffbVZHJqY4ILJNL8USyycI(ykIyGiZjB(4xVD6nB(6FCl2jiK(X(dONBw9L1SRUC1T3)B3B96)I8ilBJCAYGfRUz73GPabQGnlJbOeNegI1HcAfovmzsfq1Mg8jwMCZL)FN8lFD1f3SA7QtQRp1Gbsmg(VIL1ZYYtW5nBzA7UMUE11)(jRU(ItWXGRVPfiQxDZNwVLQL4HNda5SdxSE7TTqr(MTNS821xCI1ZH9D7AFYtjFM7(9Jf7NdS41fl0G)(bGZZbag2faTS9zR)8LF8Q1phg2)Orb8cE6TCWUdi2Pxxw0tV1dpiH)SnOZY8G2ve29eBxinr(CFyUv2Eg8jFnhek17BCbHXKHstYMMwJ5kwsVpL(xyPY6LLawJVC1N2C9QRoTR2V41237CV79E3p8E)7dUpeC075TrmR7eUPWKchZIElQEBGdMve9wi5nBd2Y6IOzfva0nwWIJ5jtcjx(UroKeJjjgAmUOeZuc9x6jaIWA9lafnYxu0yHrWgvfXMH6eFh9gBZadjyodBhjbaN7AGRToCD(EGRcfheS6E13pCD(BZU)aH7fVgdsAW(WFAXUxFuT)pTW1Pp4gOdxnhsbwDL9CawDYOvCHI5uWnSd7(ZcC96hU0u5)CoT2BAfouT9Yp(7FJGTmh46LrVvB3XWB1flkYW1wYlYtAkJ2cp8KED7Oq7gfYZ8UT(GhMLmPwPsRwQeQUexZzx1680ItXmpDmYWdI9Xf11fZpc8PQ3Xy(7yQGd7phHN0GYo2kChBrXMF39jTSfU7eX2WOyh(POGcWQBonfEQmvRV636kH9bLy(QlV(KTWgHUTRCohuoAtADKWDhje8mxeQDDLX7WYW3z2oyB4HLAXnx(NR2U(KzxE72UI6lfDyVIkt0VJubsP87JmOe07irOuc7(KqKwD3oxZdkepN4UYOIim7tiEcT39k21F8ZBUrecD(iVHdccWdu6D0S6L4HvWvJJX7hfeoW3vxgiis0iAUIrwdd9g4g6y6AfgAJNH0Ir(EUdS8DST899DCDnWW3rwE2(6nuAzWgdbByWJ0h5BAIYA5n03jWoObkCaQJehc9bdS3p6db07PlJljJ9GqV9ltl31dfWnyqOZ(Pi3bEw6Ymuamp39BKGbwH6Y43HwbUlCaWtHizzfs0QNP1apZHd9SdCSnDe0QVVREdj3BOdNwh2qRUM2KSbooUHdLqXQhAnar)WaCZj7f9GMB5XHel5oWXA)SK5GGHTc(m76YUaITSTdmTPOg0Lh6deLLtqO1qtiKG7Y2oMqPW)6omW3JhiTRhp0oSLOYHtspgg7CrZUXATdp1EYWmcawJ2bg(RCpzbg423CP9KHL33UYK6V)9JH1wV()SvTzqFYAbQ9xsjWS3DzkGcmuFkxm1UnB09En9vnoUqnUGAkxevmtDYJrZzLtZYXJfw6DvFzZMTF(K)0(uJffVlPmkV5yFHSOMZYzTplyrHqpC(Y5KY9a3l79yxUq7oc2ghMQaM9ZmWK2udgcCjbQLc86aZ5heJz)4ymEcvd17B9)Vof61pfg8teWS1PWWwdnmFkGPO5pfdoayfT5kXG2SA(egfA7szuGrAunnTukwA6u(XkvstvrB5uun(eTrfFOv4tyjIPDiTjRmoRcf2Kl8yrPWZs7tQbV2l8kgHj9hlEnJ2FuK4vu7ZynxevkPiWY4eCHH0(TYMQuo)m5itwQzYgZJEb8VLcLd76c3)wMakJL)kygPyPz4z7nUuIqAwZqKZ4BtDj57zsTIEOrkFky06nijt5uIYA6B6F6wOYmwtxhlAKRbtCXQzIoegUr0mcsdT9nYevxf10nlAygVpnJ4DxhpzNvO)qzxKw3dJA2qypWSXCYGBcqbCVa8NmopcBzLtWn0oKrrdTdsWigWpaalvnPvQsSmo9avvZ)TuX9wEGdXPvWCmcbKAYeUepkbbqdShlmqwe)SeiXhgkdCB4(Ho3PO39Y(QLzXW0I8X4LWjVSYPffWBW)CkqU5fLjf5twoBMAJHnlhNoN9(OumHft8sYWR2TcGhBkKqr97RzqrGQCOXc1NVadHXlbF5C8CLfQXgKftgVfiibAuGnkvCejeKucmYjr7EtxWkH86Hzl4Nt9uCkiMkvaLvkolPeHi2uyS2UvmPaMLPMBUs0AyHWKzLmU2tLALCdYlXBhUoBHoUZYpljLUXXzSZtuUKmBeBdnwJTVCzIMXQQeCshxvathPlWz1YKkeYmLzQKW1vKXu5M)9MTBoz(6lU8RFH6PlrOJcj4I3y5Jt9YTGnsOctyRk2c9)QJNdM8ZDOdfvX7Je7nv1jd0BtVh)bhdLVi7Ie3j84kyKegQvP1eosbAzpy7oTiF7hxKVa69g4RSBNG2EJ6BIK3jMFNrnAdqEQc7T(Ec73Bm6t1GaTXvVe2)yd71M394b(x869UCqZYXvv0QzqktIfFY5BsmpINHeSACf)rlFhJCrJsf1AKZZkcxJlxQjwumU(nS8TiLjEowWY2v4QxaPqDJItMjsSyRNy1ACL8kEHE2KbKLweXVhqwJjRejizujwe1luSEoKtPWMfKjZPgakMVxr(s4WYNWturooaHkAdVrMq)rK8IiPkyCJyh6c6HVv1uHdMjAzfnUV5ivXtGYgjgHcZfzXuflKRINitOlHq6lwt2eHNLk)L7xHUHylPhdWcNklutLLcvwj7TeFownaloQKo2EUPYfsYKraryMJSmQrIeBb1Z7WRk1IYLD0PKevY2KZlhsGd6DhlIIaseV(Kur)nq8yBc9q6zSWL5DI2aK6GyTaMuHYX(jUCmolGhdbJRcS3udN5couWWj8icojKgj9(ioPO3bkHiRjnvy(VruqPE6xQbu2pvdOSFohoz9YqPxgk9t2qPwdK6BHRSpU5AXr2xgLK38bcJPqGVk)skPVuqv9)Rt)lobqPzC6)dUVm4TjSyv6vqBW3HkBiPOZAY(dsqu9cxx8pBWo2u2iFX78BfLo5bm1O4mTKCWe8IA)LR2KiyzKusp45uDCOEPms0ExodinULd2oEkvws7oVyzvslJlpigD8qjCQJiPwkJKpbQUjrgYSn(ixf4xlzZjePYTt0yHOC6iTOQotJd7qPKak3LdOwCHIKitNaQlFQ6BucsNpVTlJAu9b1YdN6FlZ4f6H1lYq6xwYkBOMOSYifrfNXMxO(CI5hIU453QTxI6Ymw(uLCv1QDcmhYOUr7LQVQ27u4OFyIvP2AFv8svaggKwPFaCTEbI3PgGfQf0lzu8GxAlClDJFqTz5XTPYdCA7W46ZU82l)3xE1LB)ghRqwS8XTv02zskRZIetpGVuqVqFZ50w0KgQTM2R1Q2CJKtwkozqpmGaSOYNWpVAEDq(1lhVyslZqQyVgG9PpDZgXbQqFc(Tc0WdeL(a4GvXS4dm0Ol(nM45qNBQytowTcCikGfZwaZoYxCkqWr50hXb(4i(8LsGyZV)gLL1fG(4nEigRlslLDoTSMAUzDe4Fyey99IamOWVxFo4hQph2UJ3SLXLt12PBUpeiQvhcAWUXlOlK8R)hWKAF2I42dH9xZx5u(xocVm(k8TkQmbwLSMVzXMzfPQwi2Qj0OuyFSZO9Y2UjNltAOLk78f(l1H2FIhTAon2vmvMUZSNzZU(c8pJOM7LFrZjRWQwWIsOuoPtOyUQgCfb8xEf0QG432eDa6EgZf)UGk30yo9lKOAZIyZ5Q2beHEakHRQfIddH0aniM0Cf9UVX8uUgRA0etABEn3P7p76WD8wZhI7ADy31x4U(DC33yTR)Al9xtjELoS0rzcDPCWgxwud3HFJJGXU7vjFz9nFsEBUwg6PCisPxORHgXIV9x8IqmujxfvMbleWMXpgEwjQyxJcEIXIt(xCPoYtGb1cgPkATCz5KDlJsjvEX2Gu9DVvz5)tOOy(XYl2WcMPDgppB(U2AorQ346i96E6HBOdZJXhoc(4q0HNKpCoiFGvO76YKRs6PWweIvx(qNm8EaKHPCm(hS6edKV5AmJeX(mbeuSSu8xgwszfEdG8)G)Ktnkd4KBRKMKDNV9C8phTu(m98dhsC2RI7oRRA1qx)t)WRgtJr6aTNUvyFTZXe8Ky0j37uPqdiq5OqD)tK27bxcsZ6XrWYhpQ5JJpu9zpCOj(Lh6O(mZ7FwCLLWvUHFkh1thTGRoeD(bB9)mN0dhOZJa2APiCW54Hd01EHEPyWNLNigWv037q)Dh0kAzVrb2hpkW(XefGJroACG1dloONBhcdfOtP4N8OHdtRFWzVZmy7X)Z7a)DxEuKvH8Ea6qEIDr1LzkfQteHzV3iS2ZV0dRTNKAm6lFmEiPLTCEO9MJuZY9IG37uK0rdnDEINGYEVC7F)jOWlNQ1fC8JoM8W85hC3)muwp4fRCOT4Op7KTisWrBYj8K2Eytp5E8ya3xME6rhkCyA9dEpfHcUpOqHh66uEhpqW7LaHhDGWHP1pmCpRtz9iYE9aUfpBgTmzSvlBidrAfECSCAhE8OKHVeL8OJsomT(b)dLBRFO9do3whrUTnFCjVrMARxRvpc8EGZA4F84b)xIhE0XdhMw)qWdy5dNhYYh8)a6OnmBA)ufteC8yIGxIjE0XehMw)q4trkfw7nLIMfmSpuofTocwcs29bPXpAiPardUAbb6mlrylW4Edod79gF1O5WxcnF0HMHh4AdRwV9w55CfJ39Dvse(53hFwtsjgJ1FwE3GdPJxSzZRXTlxEjU8T4QUND9tLvDGYS3hNfvKJ))TN4mlp1D2poDp33Uqp7Qu59mR)CSslsKi8YXKzXdahppZ4wVHnTfyayYB)OH3PZDhMC1piXM7AvDESJ7(Q(fSgpwTJ54Xqn1PLPq4e5Cn1q8stDXJv73gRP9Bq7EhRe)ydjMOVDZtgsRrvDGuVcTZ1mtfOj4DDjKJesA3nK0slM0ufsAQIiD1JidurKUg98LASZN(rRysFTysR9ft62)3asCpQ9GrLVXTDyP13DCP1D6e4diU0(yXLIHwpHHLH6rLH)GckvtdDGyYJXyYtB7Xet6Pht6QIj9E8XKopKysZNOysZNJqsNhsiPZlHK6Kr)mw0MV8hxTE76x))d]],
  [HEALBOT_OPTIONS_RAID40]=[[TZvwZTnos439VcBpVY4IN64b9aefLe3irQHKYjEEyRsBSsIQ4inLSC2D2TS)TVDJBqXd5e7AYU1u1mLPaq39xFb0aGm5FzZ2ZYwT52Z9TpJ8WHpVB)tF7I4VTA7N3T7JNd)xX69R3U6(Zg9WVF3MpS6W6HR2FpmMd7Fy9zHFE1HNoCX)jknmnD(Gl)4Q7UF9LwSFE9axBR55tgCz4Q7pSz7No)xU)8DBp)x2EPvwuEAYSBgCjYMlTcNssgC5LwjPfXJVzG9JNnz9217xDhY80Xzr)6a7RS7Anzw6qYSrXZNhNmzGJ100IHKSPZkMoW2kVio8T3KhLKhxeFDCXndC6BnE2Y4rWyYfIAA8OOfKSIBglAzCA4Y8jzPlxKJSmIaSBuw6I8frrJg4BBvqMKxqkIsiZJgNMui1tKxzK4rswLc4cqQJ1YeadjHPZhskg4Xqbz2IPejTzltgol(3(TORJskYvSuk(fHaLb2uHqH4y1GgkmbUx5Y0OcTEPgLrrdxoEmOqJNOgCaDWdtZZLqMz1gNb6M0ejXGKNPZjVhuS(bmvH6rCa3001RUd8SOBc138OzkCqnPlIkKM(cs2KiLzbGgz27i3KNpn9DsQgJXfJZIJsgjPdib4JCifvpeQ8mCQAEGIQev07rVNIVW4znWzAP(rTtdhpEw021F9pqDxiiK9KmiqzGRLEBu7Id2eRxbh1hdfXaDrVpoN2qbj5TmIKJzg0L(qeYs2a6AfWpkjA(nmBUSjX4ycJYC6y0reLPm)MiFwqgBSo6Sop(3IG4uKqeWsPNSCofm(kQxGetnmgXjWVzWHt5O0LdNf9U4rqwDvgkMD5XZgV7dpC)K97E43Vh9bCQFU)b4Z(vFDn5UnRU)Pp(KZf)hQg5yBLqtjWjhHSvqPjZIj5IgWzFmcMshpohm02wSzigVFZ)(8F9Hv3UF1HvNxuCPfbOyi8)PllMfNer1aDj7wwYfR2(L7nenVfLS5Z68JkAVYIEX6dMsoz3HZxE)6Bp35vq8(Lfp1ZE(QT3EEXQ9FA9HQHI7RauckdfAkE1Y37vq(DklFdrF96pV5d3T(vqUDBncG1WlUG7DCu)rECrtV4cVFJwBAu4RGuDSBpiJ3YlRSHk3yZWrGLY7AXMHfwuVpqcu0Inukru8KPWkZ(awyTmH)xyTWILzawZ)6UDh(85FZ9YJzTRG1vm6tqgsa1TmRV9cVN8Fk4Pop19PEp1)PJvkBtTY5hsL4RdmMzUXAlhMcfuLLHvzYB9A45zPHVfkrmWAij8Ti7TDC5dfbta)5jidGrmXyed5TsqMgsMfHGg(9q(OkIxa8hyozzrA4S0CL3KVAHeF(nJpxj(q1Uz8Pgrt4lWwIp3QXN3ZW(9QIVUvHVBVqenjbmmrKbk0KNgdmHSqu6qwx)KqObelnmkDvz4cug0(V44l4hhF2Ajm2T7XDpoJ570JFLDWZWPNFyZh(YFqrQOgVILHVvvyp(RI0fPX4SQjPjrY2O7ReEsVVJyORKHI9uPZp4HzrJluS0XGLq3z4uuhZwVxwCkc6llMUnlgj(Qh)u17i43Rv((9zw63mFhMwuKoVfwxnIPXW17iFoCg3ymFVj0ao2gSDTOhKGe5SL)NVAZ2ZpqRTVeHUnty(67(yzs8eK4iiHVFm1UzkrH)ruyie64kttqZ0Sy)MVT6W6ZNT5(dLjTtZKIJD9(JSeDfu1PsQevgxIQETatSM2sK0Vzs41Iw2bB3mvSsjltKmSWXUsQyfb(4zKTF4Z72ZdKUzqhVR87JNUY7OtZNH7Jxi83pOtWv2D0PXTzA8y04QtIhsINZvEE1ts)R65RtJpstq3AjiOR(OdOJ25QU1dQE9VYRVonDOkIt9qYrF0D5QTNBJQTHo0JsJ7v9Qxi9CVYlqNM(in(9VY3)0PbdxQYa7A6hrWbrm3kRB34ahKvlZk1LvEROCx3Ew4QKUbSQDv16oAZQpTB7Q7UuX6BVW9jZYRDSFI2BX6)1b9DmWeKCti4(vQBJiIYUTP7HrB7is(wRyVtQVkLzs2IW0zYJikCojBcEuRvUtJfPVlklu7CANL(U5Kec)Wa58G3iGUKLZPm3fuT43dnKjzpZi3JFsNYD5WbMFGcyCrvbYMVz7MVU6oCQWteA89WyBRHeo0ey1rHFDS59QJnHyD1GsnMnqbuytvYnDdCA(zBjM9SRfZABxR4HV8WMxqVSyJNo9794zaMc3Dhp8lUGf2NsloThVmuO6YPHyp(wtJX0RE97znDcnvKns6(X4dbEIUZW(arty1fZtGOfxpH1h26mI80RrYhk7raJq(GP33bWz(iMgtlmwqWO4CSa(P4pHT)gMr3IFhkpvslw9yyMQvHqfGx2huJnmx2qjzI)knmsWGZkmuOYOHFAifFWCa4FIfCKRvtZO4efUShLQZoNePBbNZq5IGG9HA6brUDf8bHT6K9qo17GCQX)8I6COATN0nf01t6C60nqAmCLwSs(gr0Qi200141KNHfn4CSZzOYefNXhI05G(tnpJr6TknYU(8i)2YJco2l5g0GFc7SMmjExgElkV0Cx0FR5VWF3w2KGVAphMP1Uu2gzu0w0tPOniFWWZXqL03r)znPvuIRoVI1LMLqlZkMiNYJqpWjM2Bd1qq9cbwXmVUFxRywuNTVfzcnY0b6eFY313IXFRyov5HmOqyHv4ayE3yukXCGgZSJUWtmitOJgVsjgDuPYSEejndfOGL20br9ebQPIH1gNUHCSsq4RP0vxec0TQ0hmcjnziEhzIRXCsAk8R0hoGxqE2QTFcVHQjjPzrPjJxoBMC7JYsLMoN8(WPynE24DzH3Wk9YMbEx8(cc0skE1y0FFZc62iy06oGE)ZzXlWtNgPdwgmdwKBg)OHHO9iTBOCbjd2ibRBCxeCKZ7NOklJdT34BLEDugYygrtvYLmdukCLxq(O0fvXb4uWhANKjqrS4DYweVW8KQrUiypWBnJaLgDvpCgjp3eTcTzCkSunEjUCSHlaRWcIUOCeF5QZ6LvwA2U)XUd7oF(6B38WxVuIeo)G9uZ0qATbSgDXJGx61Kn7mWXbphRAo0DdxfDNCLSgcGX3DOsVHP(ewzc7bpGDIQLTi1js8AAhMdtqKtdv0ng5lNJgd4PrHy9(3)HDB3U(dhwFlGJQSlpQfV7(keVRI0AiCVs4Qc8vA4psmVwM3jh0xkLZWaxvGVMZO6iFvq8PeYFuEIwKVwGY)dg67urOVkx(0I8vsxBgjTzoBjEV81kPn3VCfX8C6kE(Y6RsyNhxsOC9MC2JoqfBjYIWuRgfgsvw(lKJmSmCe)a55fOWkR5Q(D7GnrV5pQTGF8DmUWwKd6IvgHvcBKPHSQZyRCJuY7pNVszqF(k3GdxkgASfQkSb543h4lTqm66Ki74IBQ2iydXgcV5cBAeTsesSq40)2JvGYvobILRHEOPoYtTfpXlq6sgMWxToFe3IKZQnOVVdIr6l8LOGXi6ptykvFWYdTGx2qIgTzcAlz6tygNoEOKq9mrI0eHHJjoiwd9dcHYQveeXeMiY0s7fUtnF2ugtYfJFAixAHIlNmr4714ejKWEtRsygsFm(AiVaQ8qk(cCrZpZGicJeJMeZDAKqHzxeuQzTOkwIGySUQUuJhnuvbqDhwIitiNsmwBLVnVKy0ysq278OzgK7FLb9xzq)vgufzqueEkjrvTkvmuLe)cbYcJsKV6Cxlk2c2JN(ZGZtwbXO4W0K8fKWi0DpMmkY8f0uXoKSJ7FQSibwuHC98HgmoluaGEwq9JxxIk2B5NjNfJb23Vsi4GzfjX2WZOyTYLWIbdnzchoEaay3qmBVOmkNNUmxv6iuvgdZd6WkgdvDXBCOtGYqGupnnViwHy0UKhfMJ1vMfQGlOQQFOvHNd7hcv0jG9BoAdSgjalEwphzFaUkTbQXXuyd(l61NIzZZcL2coiPsYCfcgKfkEcmmSOeizfeT0dtT3rGDizIPpivbvQeeMaxlHEiETNd5mRdvl5wzENI4nHDfeT0fYvwnxk0RgTJKw9hLzhU1NDu2Dxz8rvrQQOkFZ0QQtwKdo4uZwCcmtxo2R9AKSyoPq5jc0tu0Nx57njP8ejArfNywc4)lfzzMmuk1VCq7jLROhvRLa2EAYXrnhprGwgIrsOX8hpZue9WV2Zo8Qj7Ww5IposyuPj3kbTAZgAi)Q9mc3)CwaXmNWiwxLq07OG5Js8BmXiO(vpAlRqleslC)Kw8iO8IhLNL3mBWi8T9fn8Qk)6Kw3qLOBMCF8KGTLAeCQPgAtOhisokDBgYQTSRnL5Ly9KGxPfuC)FKfuSFgRN4(cVEs3tB5KU))8QjUFpRMGVrzy(b)0Y(1LKmfoJZcvOEumzEQ6t2s)9AFEAQ0TxKftsMOilVqDu05Vv70MdZuFStA4O6R0b7sDNoJwM9osgEIJOfqDaXutN88vPg(LzftZMoOp9R)kor7Rbt)DpqByMLXx3XyI9zWHCJFPartmqPgkvihA0W)AYywl6Jj)yk0A4rLLR27k76n3V5FS5Unh(dM1ng2FoD6WC6h0quwrCO4P0q6naIFgI0lvqiLYSX9uytq78X7u4tV24ZX3UTPoB)9J28D75bL5l53lEhmDd4LYRHFgIS(8SGHTySmSxXbxno40ahCfCOmio6JSqdD2Am3VbM7xbZjF6t73Xur6HI4WMHeFFEaGsFxhc8OVEpYB9qFUb8z98oMTnbFh3PNftVESMg4AinCVF81SusQEPOX1H81ipsOgsqzT0LAxuQOVURPKD(U0p6HcwHU175PBpBjC7f9n0kADpNKafZIiyltk1Anjp8VaXO9n3G3t1mYnSZvvS2dRn2bqA0uweumwb7k9KZCs7Ab)k(GbnfMzCgD2rZHCJ4mnnyP47L1CO6Fr0gdNMnZtf1vMJNRSSUAxwznLOXXT(IQUMT2U(A2JX0xXBVf)Nea57M8czTReALF0VJKu29Fk7bRDa)l)vyalnd(7c67JIV1C6FdSwqB32Ao9VDTiYYHMZyThqc9bOfgRwW(dH9fjBrRjcLa93DTMpLXXCjNiuE)gGswxgkufEqt11(u0xNM13UC9TBj9fW0rkSRqHTf4vOXcnLW5LsdL6mVhUg7XnzpEw0xxV)tIxXxhl9nRWp6BzH00d62H(MqzDTSCZWSyyHoYm2lBmu0jYyFXRXf)99jLW2WcVkf67SmelYhT5UJenkQXdqL4nDUYpzpR4K)g00iAjRX87tHUFD6eXwI7FrCOv4BITqRDF916F2u6JwKxgby3MXWJzmCnng26gdPTWRfBrq72cbg0ngoLng6wIUNIPWwmp9F3r)R9NP2j72sx8c2uv6S0Lz8LULPtzYx5a(c6Qzh5Vgle65JSaFNXX5aiS)rormFPuY03JvnC4zIJf7(NR3Z(EGLarcIjAIOAWGGqaOHSjJQhivSgfZ0OhpuHHXWOyAl4bDbCygW(eaeVxBm9Swm5wHBbwY0q6U6Uf3wDlENMBXv)Feg0LCMUKLsv5hGcABZr41SJW1iVuhq9AjcTeGQYrObtDaL1gG6Bae5xToD)sAGjRM0fx2hIopyONkMvZNya3AbJNwirzP)YKSg0KWRTwogWSRYdvDiZqUql7yCLgLjNSrX)ptJIFnhgaV7GVdS5(SWwdHUbnJTo)qt7)gh32MHbgrTyRtZyR7ZfBEgyZVoOrpEtk48RhBDBiqVBTb6vTMGqK1SQG(eqtoLOTEpxZI)lOzPxdMLEplZI)lSzP)FMrY9BmsgpVqrbwasgA(gWcTWFRz0UmX0z85m556WttgO9XgYlDSF9)tFc)LjfiKWM1r7Ro0awTIC32qEVgGUBjO)ghT3b2kF5CRh5UpAcRwrU3pN2CV2rU)pNi3VDKh8ZjYdAh5D(5e5DAh5D)5e5DBh59(5e59Ah59)5e51Tsu4UV(73T(W6l(Vp]],
}

HealBot_Config_SkinsDefaults = {
  Skin_ID = 1,
  Current_Skin = HEALBOT_SKINS_STD,
  Skins = {HEALBOT_SKINS_STD, HEALBOT_OPTIONS_GROUPHEALS, HEALBOT_OPTIONS_RAID25, HEALBOT_OPTIONS_RAID40},
  DuplicateBars = {},
  Author = {},
  Chat = {},
  General = {},
  Healing = {},
  BarAggro = {},
  BarSort = {},
  BarVisibility = {},
  FocusGroups = {},
  FrameAlias = {},
  FrameAliasBar = {},
  Frame = {},
  StickyFrames = {},
  HealGroups = {},
  Anchors = {},
  HeadBar = {},
  HeadText = {},
  AuxBarFrame = {},
  AuxBar = {},
  AuxBarText = {},
  HealBar = {},
  BarCol = {},
  BarIACol = {},
  BarText = {},
  BarTextCol = {},
  Icons = {},
  RaidIcon = {},
  IconText = {},
  IconSets = {},
  IconSetsText = {},
  Enemy = {},
  Indicators = {},
  Emerg = {},
  ToolTip = {},
};



HealBot_Config = {};
HealBot_Globals = {};
Healbot_Config_Skins = {};
HealBot_Config_Spells = {};
HealBot_Config_Buffs = {};
HealBot_Config_Cures = {};
HealBot_Class_Spells = {};
HealBot_Class_Buffs = {};
HealBot_Class_Cures = {};
HealBot_customTempUserName={}

HealBot_Data={  ["TIPBUTTON"] = false,
                ["TIPTYPE"] = "NONE",
                ["TIPUSE"] = false,
                ["UILOCK"] = false,
                ["PCLASSTRIM"] = "",
                ["PNAME"] = "",
                ["INSPECT"] = false,
                ["MAPID"] = 0,
                ["UNITSLOCK"] = false,
                ["POWERTYPE"]= 0,
                ["PLAYERGROUP"]= 1,
                ["PUNIT"]="player",
};

HealBot_Unit_Status={   ["DISABLED"]=0,
                        ["CHECK"]=2,
                        ["ENABLEDOOR"]=3,
                        ["ENABLEDIR"]=4,
                        ["BUFFNOCOL"]=5,
                        ["BUFFBARCOL"]=6,
                        ["DEBUFFNOCOL"]=7,
                        ["DEBUFFBARCOL"]=8,
                        ["PLUGINBARCOL"]=15,
                        ["DEAD"]=18,
                        ["RES"]=19,
                        ["DC"]=50,
                        ["RESERVED"]=99,
}

HealBot_Spell_IDs = {};
HealBot_Spell_Names = {};
HealBot_Unit_Button={};
HealBot_Private_Button={};
HealBot_Enemy_Button={};
HealBot_Extra_Button={};
HealBot_Pet_Button={};
HealBot_Vehicle_Button={};
HealBot_Emerg_Button={};
HealBot_Buttons={};
HealBot_Test_Button={};

